CREATE OR REPLACE VIEW silver.V_tbl_clcl_claim AS
SELECT
  trim(tbl.AGAG_ID) as AGAG_ID,
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_ACD_AMT) as CLCL_ACD_AMT,
  trim(tbl.CLCL_ACD_DT) as CLCL_ACD_DT,
  trim(tbl.CLCL_ACD_IND) as CLCL_ACD_IND,
  trim(tbl.CLCL_ACD_STATE) as CLCL_ACD_STATE,
  trim(tbl.CLCL_ACPT_DTM) as CLCL_ACPT_DTM,
  trim(tbl.CLCL_AG_SOURCE) as CLCL_AG_SOURCE,
  trim(tbl.CLCL_AIAI_EOB_IND) as CLCL_AIAI_EOB_IND,
  trim(tbl.CLCL_BATCH_ACTION) as CLCL_BATCH_ACTION,
  trim(tbl.CLCL_BATCH_ID) as CLCL_BATCH_ID,
  trim(tbl.CLCL_CAP_IND) as CLCL_CAP_IND,
  trim(tbl.CLCL_CE_IND) as CLCL_CE_IND,
  trim(tbl.CLCL_CL_SUB_TYPE) as CLCL_CL_SUB_TYPE,
  trim(tbl.CLCL_CL_TYPE) as CLCL_CL_TYPE,
  trim(tbl.CLCL_COB_EOB_IND) as CLCL_COB_EOB_IND,
  trim(tbl.CLCL_COBRA_IND) as CLCL_COBRA_IND,
  trim(tbl.CLCL_CUR_STS) as CLCL_CUR_STS,
  trim(tbl.CLCL_CURR_ILL_DT) as CLCL_CURR_ILL_DT,
  trim(tbl.CLCL_DRAG_DT) as CLCL_DRAG_DT,
  trim(tbl.CLCL_DRAG_OR_IND) as CLCL_DRAG_OR_IND,
  trim(tbl.CLCL_EOB_EXCD_ID) as CLCL_EOB_EXCD_ID,
  trim(tbl.CLCL_EXT_AUTH_NO) as CLCL_EXT_AUTH_NO,
  trim(tbl.CLCL_EXT_REF_IND) as CLCL_EXT_REF_IND,
  trim(tbl.CLCL_HIGH_SVC_DT) as CLCL_HIGH_SVC_DT,
  trim(tbl.CLCL_HSA_IND) as CLCL_HSA_IND,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLCL_ID_ADJ_FROM) as CLCL_ID_ADJ_FROM,
  trim(tbl.CLCL_ID_ADJ_TO) as CLCL_ID_ADJ_TO,
  trim(tbl.CLCL_ID_CRTE_FROM) as CLCL_ID_CRTE_FROM,
  trim(tbl.CLCL_INPUT_DT) as CLCL_INPUT_DT,
  trim(tbl.CLCL_INPUT_METH) as CLCL_INPUT_METH,
  trim(tbl.CLCL_LAST_ACT_DTM) as CLCL_LAST_ACT_DTM,
  trim(tbl.CLCL_LOCK_TOKEN) as CLCL_LOCK_TOKEN,
  trim(tbl.CLCL_LOW_SVC_DT) as CLCL_LOW_SVC_DT,
  trim(tbl.CLCL_ME_AGE) as CLCL_ME_AGE,
  trim(tbl.CLCL_MECD_RESUB_NO) as CLCL_MECD_RESUB_NO,
  trim(tbl.CLCL_MED_ASSGN_IND) as CLCL_MED_ASSGN_IND,
  trim(tbl.CLCL_MICRO_ID) as CLCL_MICRO_ID,
  trim(tbl.CLCL_NEXT_REV_DT) as CLCL_NEXT_REV_DT,
  trim(tbl.CLCL_NTWK_IND) as CLCL_NTWK_IND,
  trim(tbl.CLCL_OOA_IND) as CLCL_OOA_IND,
  trim(tbl.CLCL_OTHER_BN_IND) as CLCL_OTHER_BN_IND,
  trim(tbl.CLCL_OUT_LAB_IND) as CLCL_OUT_LAB_IND,
  trim(tbl.CLCL_PA_ACCT_NO) as CLCL_PA_ACCT_NO,
  trim(tbl.CLCL_PA_PAID_AMT) as CLCL_PA_PAID_AMT,
  trim(tbl.CLCL_PAID_DT) as CLCL_PAID_DT,
  trim(tbl.CLCL_PAP_EOB_IND) as CLCL_PAP_EOB_IND,
  trim(tbl.CLCL_PAY_PR_IND) as CLCL_PAY_PR_IND,
  trim(tbl.CLCL_PAYEE_PR_ID) as CLCL_PAYEE_PR_ID,
  trim(tbl.CLCL_PCA_IND) as CLCL_PCA_IND,
  trim(tbl.CLCL_PCP_IND) as CLCL_PCP_IND,
  trim(tbl.CLCL_PR_SS_EIN_IND) as CLCL_PR_SS_EIN_IND,
  trim(tbl.CLCL_PRE_PRICE_IND) as CLCL_PRE_PRICE_IND,
  trim(tbl.CLCL_PROG_COV_IND_NVL) as CLCL_PROG_COV_IND_NVL,
  trim(tbl.CLCL_PRPR_ID_PCP) as CLCL_PRPR_ID_PCP,
  trim(tbl.CLCL_PRPR_ID_REF) as CLCL_PRPR_ID_REF,
  trim(tbl.CLCL_RAD_ENC_IND) as CLCL_RAD_ENC_IND,
  trim(tbl.CLCL_REC_ENC_IND) as CLCL_REC_ENC_IND,
  trim(tbl.CLCL_RECD_DT) as CLCL_RECD_DT,
  trim(tbl.CLCL_REL_CLCL_ID) as CLCL_REL_CLCL_ID,
  trim(tbl.CLCL_REL_INFO_IND) as CLCL_REL_INFO_IND,
  trim(tbl.CLCL_RELHP_FROM_DT) as CLCL_RELHP_FROM_DT,
  trim(tbl.CLCL_RELHP_TO_DT) as CLCL_RELHP_TO_DT,
  trim(tbl.CLCL_SEC_ADJUD_NVL) as CLCL_SEC_ADJUD_NVL,
  trim(tbl.CLCL_SIMI_ILL_DT) as CLCL_SIMI_ILL_DT,
  trim(tbl.CLCL_SITE) as CLCL_SITE,
  trim(tbl.CLCL_TOT_CHG) as CLCL_TOT_CHG,
  trim(tbl.CLCL_TOT_PAYABLE) as CLCL_TOT_PAYABLE,
  trim(tbl.CLCL_UNABL_FROM_DT) as CLCL_UNABL_FROM_DT,
  trim(tbl.CLCL_UNABL_TO_DT) as CLCL_UNABL_TO_DT,
  trim(tbl.CLST_MCTR_REAS) as CLST_MCTR_REAS,
  trim(tbl.CLST_SEQ_NO) as CLST_SEQ_NO,
  trim(tbl.CSCS_ID) as CSCS_ID,
  trim(tbl.CSPD_CAT) as CSPD_CAT,
  trim(tbl.CSPI_ID) as CSPI_ID,
  trim(tbl.GRGR_CK) as GRGR_CK,
  trim(tbl.MDPC_PFX) as MDPC_PFX,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.MEME_HICN) as MEME_HICN,
  trim(tbl.MEME_RECORD_NO) as MEME_RECORD_NO,
  trim(tbl.MEME_REL) as MEME_REL,
  trim(tbl.MEME_SEX) as MEME_SEX,
  trim(tbl.MEPE_FI) as MEPE_FI,
  trim(tbl.MEPE_PLAN_ENTRY_DT) as MEPE_PLAN_ENTRY_DT,
  trim(tbl.NWCR_PFX) as NWCR_PFX,
  trim(tbl.NWNW_ID) as NWNW_ID,
  trim(tbl.NWPE_PFX) as NWPE_PFX,
  trim(tbl.NWPR_PFX) as NWPR_PFX,
  trim(tbl.PCAG_PFX) as PCAG_PFX,
  trim(tbl.PDBC_PFX_NPPR) as PDBC_PFX_NPPR,
  trim(tbl.PDBC_PFX_SEDF) as PDBC_PFX_SEDF,
  trim(tbl.PDDS_MCTR_BCAT) as PDDS_MCTR_BCAT,
  trim(tbl.PDDS_PROD_TYPE) as PDDS_PROD_TYPE,
  trim(tbl.PDPD_ID) as PDPD_ID,
  trim(tbl.PGPI_ID) as PGPI_ID,
  trim(tbl.PRAC_PFX) as PRAC_PFX,
  trim(tbl.PRAD_TYPE) as PRAD_TYPE,
  trim(tbl.PRPR_ID) as PRPR_ID,
  trim(tbl.PZAP_ID) as PZAP_ID,
  trim(tbl.SBSB_CK) as SBSB_CK,
  trim(tbl.SGSG_CK) as SGSG_CK,
  trim(tbl.SYS_BITMAP_NVL) as SYS_BITMAP_NVL,
  trim(tbl.SYS_LAST_OFFSET_NVL) as SYS_LAST_OFFSET_NVL,
  trim(tbl.USUS_ID) as USUS_ID
FROM bronze.tbl_clcl_claim tbl
GROUP BY
  trim(AGAG_ID),
  trim(ATXR_SOURCE_ID),
  trim(CLCL_ACD_AMT),
  trim(CLCL_ACD_DT),
  trim(CLCL_ACD_IND),
  trim(CLCL_ACD_STATE),
  trim(CLCL_ACPT_DTM),
  trim(CLCL_AG_SOURCE),
  trim(CLCL_AIAI_EOB_IND),
  trim(CLCL_BATCH_ACTION),
  trim(CLCL_BATCH_ID),
  trim(CLCL_CAP_IND),
  trim(CLCL_CE_IND),
  trim(CLCL_CL_SUB_TYPE),
  trim(CLCL_CL_TYPE),
  trim(CLCL_COB_EOB_IND),
  trim(CLCL_COBRA_IND),
  trim(CLCL_CUR_STS),
  trim(CLCL_CURR_ILL_DT),
  trim(CLCL_DRAG_DT),
  trim(CLCL_DRAG_OR_IND),
  trim(CLCL_EOB_EXCD_ID),
  trim(CLCL_EXT_AUTH_NO),
  trim(CLCL_EXT_REF_IND),
  trim(CLCL_HIGH_SVC_DT),
  trim(CLCL_HSA_IND),
  trim(CLCL_ID),
  trim(CLCL_ID_ADJ_FROM),
  trim(CLCL_ID_ADJ_TO),
  trim(CLCL_ID_CRTE_FROM),
  trim(CLCL_INPUT_DT),
  trim(CLCL_INPUT_METH),
  trim(CLCL_LAST_ACT_DTM),
  trim(CLCL_LOCK_TOKEN),
  trim(CLCL_LOW_SVC_DT),
  trim(CLCL_ME_AGE),
  trim(CLCL_MECD_RESUB_NO),
  trim(CLCL_MED_ASSGN_IND),
  trim(CLCL_MICRO_ID),
  trim(CLCL_NEXT_REV_DT),
  trim(CLCL_NTWK_IND),
  trim(CLCL_OOA_IND),
  trim(CLCL_OTHER_BN_IND),
  trim(CLCL_OUT_LAB_IND),
  trim(CLCL_PA_ACCT_NO),
  trim(CLCL_PA_PAID_AMT),
  trim(CLCL_PAID_DT),
  trim(CLCL_PAP_EOB_IND),
  trim(CLCL_PAY_PR_IND),
  trim(CLCL_PAYEE_PR_ID),
  trim(CLCL_PCA_IND),
  trim(CLCL_PCP_IND),
  trim(CLCL_PR_SS_EIN_IND),
  trim(CLCL_PRE_PRICE_IND),
  trim(CLCL_PROG_COV_IND_NVL),
  trim(CLCL_PRPR_ID_PCP),
  trim(CLCL_PRPR_ID_REF),
  trim(CLCL_RAD_ENC_IND),
  trim(CLCL_REC_ENC_IND),
  trim(CLCL_RECD_DT),
  trim(CLCL_REL_CLCL_ID),
  trim(CLCL_REL_INFO_IND),
  trim(CLCL_RELHP_FROM_DT),
  trim(CLCL_RELHP_TO_DT),
  trim(CLCL_SEC_ADJUD_NVL),
  trim(CLCL_SIMI_ILL_DT),
  trim(CLCL_SITE),
  trim(CLCL_TOT_CHG),
  trim(CLCL_TOT_PAYABLE),
  trim(CLCL_UNABL_FROM_DT),
  trim(CLCL_UNABL_TO_DT),
  trim(CLST_MCTR_REAS),
  trim(CLST_SEQ_NO),
  trim(CSCS_ID),
  trim(CSPD_CAT),
  trim(CSPI_ID),
  trim(GRGR_CK),
  trim(MDPC_PFX),
  trim(MEME_CK),
  trim(MEME_HICN),
  trim(MEME_RECORD_NO),
  trim(MEME_REL),
  trim(MEME_SEX),
  trim(MEPE_FI),
  trim(MEPE_PLAN_ENTRY_DT),
  trim(NWCR_PFX),
  trim(NWNW_ID),
  trim(NWPE_PFX),
  trim(NWPR_PFX),
  trim(PCAG_PFX),
  trim(PDBC_PFX_NPPR),
  trim(PDBC_PFX_SEDF),
  trim(PDDS_MCTR_BCAT),
  trim(PDDS_PROD_TYPE),
  trim(PDPD_ID),
  trim(PGPI_ID),
  trim(PRAC_PFX),
  trim(PRAD_TYPE),
  trim(PRPR_ID),
  trim(PZAP_ID),
  trim(SBSB_CK),
  trim(SGSG_CK),
  trim(SYS_BITMAP_NVL),
  trim(SYS_LAST_OFFSET_NVL),
  trim(USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_clcb_cl_cob AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCB_COB_ALLOW) as CLCB_COB_ALLOW,
  trim(tbl.CLCB_COB_AMT) as CLCB_COB_AMT,
  trim(tbl.CLCB_COB_COINS_AMT) as CLCB_COB_COINS_AMT,
  trim(tbl.CLCB_COB_COPAY_AMT) as CLCB_COB_COPAY_AMT,
  trim(tbl.CLCB_COB_DED_AMT) as CLCB_COB_DED_AMT,
  trim(tbl.CLCB_COB_DISALLOW) as CLCB_COB_DISALLOW,
  trim(tbl.CLCB_COB_PAID_DT_NVL) as CLCB_COB_PAID_DT_NVL,
  trim(tbl.CLCB_COB_SANCTION) as CLCB_COB_SANCTION,
  trim(tbl.CLCB_COB_TYPE) as CLCB_COB_TYPE,
  trim(tbl.CLCB_LOCK_TOKEN) as CLCB_LOCK_TOKEN,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clcb_cl_cob tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CLCB_COB_ALLOW),
  trim(CLCB_COB_AMT),
  trim(CLCB_COB_COINS_AMT),
  trim(CLCB_COB_COPAY_AMT),
  trim(CLCB_COB_DED_AMT),
  trim(CLCB_COB_DISALLOW),
  trim(CLCB_COB_PAID_DT_NVL),
  trim(CLCB_COB_SANCTION),
  trim(CLCB_COB_TYPE),
  trim(CLCB_LOCK_TOKEN),
  trim(CLCL_ID),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_clov_overpay AS
SELECT
  trim(tbl.ACPR_REF_ID) as ACPR_REF_ID,
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_CL_SUB_TYPE) as CLCL_CL_SUB_TYPE,
  trim(tbl.CLCL_CL_TYPE) as CLCL_CL_TYPE,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLOV_AMT) as CLOV_AMT,
  trim(tbl.CLOV_AUTO_REDUC) as CLOV_AUTO_REDUC,
  trim(tbl.CLOV_CREATE_DT) as CLOV_CREATE_DT,
  trim(tbl.CLOV_LOCK_TOKEN) as CLOV_LOCK_TOKEN,
  trim(tbl.CLOV_ORIG_HSA_AMT) as CLOV_ORIG_HSA_AMT,
  trim(tbl.CLOV_PAYEE_IND) as CLOV_PAYEE_IND,
  trim(tbl.LOBD_ID) as LOBD_ID,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.PRPR_ID) as PRPR_ID,
  trim(tbl.SBSB_CK) as SBSB_CK
FROM bronze.tbl_clov_overpay tbl
GROUP BY
  trim(ACPR_REF_ID),
  trim(ATXR_SOURCE_ID),
  trim(CLCL_CL_SUB_TYPE),
  trim(CLCL_CL_TYPE),
  trim(CLCL_ID),
  trim(CLOV_AMT),
  trim(CLOV_AUTO_REDUC),
  trim(CLOV_CREATE_DT),
  trim(CLOV_LOCK_TOKEN),
  trim(CLOV_ORIG_HSA_AMT),
  trim(CLOV_PAYEE_IND),
  trim(LOBD_ID),
  trim(MEME_CK),
  trim(PRPR_ID),
  trim(SBSB_CK);
CREATE OR REPLACE VIEW silver.V_tbl_clhi_proc AS
SELECT
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLHI_IP_DT) as CLHI_IP_DT,
  trim(tbl.CLHI_IPCD_MAN_IND) as CLHI_IPCD_MAN_IND,
  trim(tbl.CLHI_LOCK_TOKEN) as CLHI_LOCK_TOKEN,
  trim(tbl.CLHI_TYPE) as CLHI_TYPE,
  trim(tbl.IPCD_ID) as IPCD_ID,
  trim(tbl.IPCD_ID_SUB) as IPCD_ID_SUB,
  trim(tbl.IPCD_ID_TRANS) as IPCD_ID_TRANS,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clhi_proc tbl
GROUP BY
  trim(CLCL_ID),
  trim(CLHI_IP_DT),
  trim(CLHI_IPCD_MAN_IND),
  trim(CLHI_LOCK_TOKEN),
  trim(CLHI_TYPE),
  trim(IPCD_ID),
  trim(IPCD_ID_SUB),
  trim(IPCD_ID_TRANS),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_mcre_relat_ent AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.MCRE_ADDR1) as MCRE_ADDR1,
  trim(tbl.MCRE_ADDR2) as MCRE_ADDR2,
  trim(tbl.MCRE_ADDR3) as MCRE_ADDR3,
  trim(tbl.MCRE_CITY) as MCRE_CITY,
  trim(tbl.MCRE_CITY_XLOW) as MCRE_CITY_XLOW,
  trim(tbl.MCRE_COUNTY) as MCRE_COUNTY,
  trim(tbl.MCRE_CTRY_CD) as MCRE_CTRY_CD,
  trim(tbl.MCRE_DESC) as MCRE_DESC,
  trim(tbl.MCRE_EMAIL) as MCRE_EMAIL,
  trim(tbl.MCRE_EXTN_ADDR_IND) as MCRE_EXTN_ADDR_IND,
  trim(tbl.MCRE_FAX) as MCRE_FAX,
  trim(tbl.MCRE_FAX_EXT) as MCRE_FAX_EXT,
  trim(tbl.MCRE_ID) as MCRE_ID,
  trim(tbl.MCRE_LOCK_TOKEN) as MCRE_LOCK_TOKEN,
  trim(tbl.MCRE_MCTR_CODE) as MCRE_MCTR_CODE,
  trim(tbl.MCRE_MCTR_LANG) as MCRE_MCTR_LANG,
  trim(tbl.MCRE_NAME) as MCRE_NAME,
  trim(tbl.MCRE_NAME_XLOW) as MCRE_NAME_XLOW,
  trim(tbl.MCRE_PHONE) as MCRE_PHONE,
  trim(tbl.MCRE_PHONE_EXT) as MCRE_PHONE_EXT,
  trim(tbl.MCRE_STATE) as MCRE_STATE,
  trim(tbl.MCRE_TYPE) as MCRE_TYPE,
  trim(tbl.MCRE_ZIP) as MCRE_ZIP,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_mcre_relat_ent tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(MCRE_ADDR1),
  trim(MCRE_ADDR2),
  trim(MCRE_ADDR3),
  trim(MCRE_CITY),
  trim(MCRE_CITY_XLOW),
  trim(MCRE_COUNTY),
  trim(MCRE_CTRY_CD),
  trim(MCRE_DESC),
  trim(MCRE_EMAIL),
  trim(MCRE_EXTN_ADDR_IND),
  trim(MCRE_FAX),
  trim(MCRE_FAX_EXT),
  trim(MCRE_ID),
  trim(MCRE_LOCK_TOKEN),
  trim(MCRE_MCTR_CODE),
  trim(MCRE_MCTR_LANG),
  trim(MCRE_NAME),
  trim(MCRE_NAME_XLOW),
  trim(MCRE_PHONE),
  trim(MCRE_PHONE_EXT),
  trim(MCRE_STATE),
  trim(MCRE_TYPE),
  trim(MCRE_ZIP),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_acrh_red_hist AS
SELECT
  trim(tbl.ACPR_REF_ID) as ACPR_REF_ID,
  trim(tbl.ACPR_SUB_TYPE) as ACPR_SUB_TYPE,
  trim(tbl.ACRH_AMT) as ACRH_AMT,
  trim(tbl.ACRH_CREATE_DT) as ACRH_CREATE_DT,
  trim(tbl.ACRH_EVENT_TYPE) as ACRH_EVENT_TYPE,
  trim(tbl.ACRH_LOCK_TOKEN) as ACRH_LOCK_TOKEN,
  trim(tbl.ACRH_MCTR_RSN) as ACRH_MCTR_RSN,
  trim(tbl.ACRH_PER_END_DT) as ACRH_PER_END_DT,
  trim(tbl.ACRH_RCVD_CKNO) as ACRH_RCVD_CKNO,
  trim(tbl.ACRH_RECD_DT) as ACRH_RECD_DT,
  trim(tbl.ACRH_SEQ_NO) as ACRH_SEQ_NO,
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CKPY_REF_ID) as CKPY_REF_ID,
  trim(tbl.USUS_ID) as USUS_ID
FROM bronze.tbl_acrh_red_hist tbl
GROUP BY
  trim(ACPR_REF_ID),
  trim(ACPR_SUB_TYPE),
  trim(ACRH_AMT),
  trim(ACRH_CREATE_DT),
  trim(ACRH_EVENT_TYPE),
  trim(ACRH_LOCK_TOKEN),
  trim(ACRH_MCTR_RSN),
  trim(ACRH_PER_END_DT),
  trim(ACRH_RCVD_CKNO),
  trim(ACRH_RECD_DT),
  trim(ACRH_SEQ_NO),
  trim(ATXR_SOURCE_ID),
  trim(CKPY_REF_ID),
  trim(USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_clmf_mult_func AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLMF_EXT_PREATH_NO) as CLMF_EXT_PREATH_NO,
  trim(tbl.CLMF_EXT_REFRAL_NO) as CLMF_EXT_REFRAL_NO,
  trim(tbl.CLMF_ICD_IND_PROC) as CLMF_ICD_IND_PROC,
  trim(tbl.CLMF_ICD_QUAL_IND) as CLMF_ICD_QUAL_IND,
  trim(tbl.CLMF_INPUT_HLTH_ID) as CLMF_INPUT_HLTH_ID,
  trim(tbl.CLMF_INPUT_SBSB_ID) as CLMF_INPUT_SBSB_ID,
  trim(tbl.CLMF_INPUT_TXNM_CD) as CLMF_INPUT_TXNM_CD,
  trim(tbl.CLMF_LOCK_TOKEN) as CLMF_LOCK_TOKEN,
  trim(tbl.CLMF_PRPR_FA_NPI) as CLMF_PRPR_FA_NPI,
  trim(tbl.CLMF_PRPR_FA_TAX) as CLMF_PRPR_FA_TAX,
  trim(tbl.CLMF_PRPR_ID_FAC) as CLMF_PRPR_ID_FAC,
  trim(tbl.CLMF_PRPR_RF_NPI) as CLMF_PRPR_RF_NPI,
  trim(tbl.CLMF_PRPR_RF_TAX) as CLMF_PRPR_RF_TAX,
  trim(tbl.CLMF_PRPR_SE_ENTY_NVL) as CLMF_PRPR_SE_ENTY_NVL,
  trim(tbl.CLMF_PRPR_SE_NPI) as CLMF_PRPR_SE_NPI,
  trim(tbl.CLMF_PRPR_SE_SPEC_NVL) as CLMF_PRPR_SE_SPEC_NVL,
  trim(tbl.CLMF_PRPR_SE_SPEC2_NVL) as CLMF_PRPR_SE_SPEC2_NVL,
  trim(tbl.CLMF_PRPR_SE_TAX) as CLMF_PRPR_SE_TAX,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID,
  trim(tbl.TEIN_ID) as TEIN_ID
FROM bronze.tbl_clmf_mult_func tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CLCL_ID),
  trim(CLMF_EXT_PREATH_NO),
  trim(CLMF_EXT_REFRAL_NO),
  trim(CLMF_ICD_IND_PROC),
  trim(CLMF_ICD_QUAL_IND),
  trim(CLMF_INPUT_HLTH_ID),
  trim(CLMF_INPUT_SBSB_ID),
  trim(CLMF_INPUT_TXNM_CD),
  trim(CLMF_LOCK_TOKEN),
  trim(CLMF_PRPR_FA_NPI),
  trim(CLMF_PRPR_FA_TAX),
  trim(CLMF_PRPR_ID_FAC),
  trim(CLMF_PRPR_RF_NPI),
  trim(CLMF_PRPR_RF_TAX),
  trim(CLMF_PRPR_SE_ENTY_NVL),
  trim(CLMF_PRPR_SE_NPI),
  trim(CLMF_PRPR_SE_SPEC_NVL),
  trim(CLMF_PRPR_SE_SPEC2_NVL),
  trim(CLMF_PRPR_SE_TAX),
  trim(MEME_CK),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID),
  trim(TEIN_ID);
CREATE OR REPLACE VIEW silver.V_tbl_mctr_cd_trans AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.MCTR_DESC) as MCTR_DESC,
  trim(tbl.MCTR_ENTITY) as MCTR_ENTITY,
  trim(tbl.MCTR_FILTER) as MCTR_FILTER,
  trim(tbl.MCTR_LOCK_TOKEN) as MCTR_LOCK_TOKEN,
  trim(tbl.MCTR_SORT) as MCTR_SORT,
  trim(tbl.MCTR_TYPE) as MCTR_TYPE,
  trim(tbl.MCTR_VALUE) as MCTR_VALUE,
  trim(tbl.MCTR_VALUE_SIZE) as MCTR_VALUE_SIZE,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_mctr_cd_trans tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(MCTR_DESC),
  trim(MCTR_ENTITY),
  trim(MCTR_FILTER),
  trim(MCTR_LOCK_TOKEN),
  trim(MCTR_SORT),
  trim(MCTR_TYPE),
  trim(MCTR_VALUE),
  trim(MCTR_VALUE_SIZE),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_clis_its_subsc AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLIS_ADDL_DATA) as CLIS_ADDL_DATA,
  trim(tbl.CLIS_ADDR1) as CLIS_ADDR1,
  trim(tbl.CLIS_ADDR2) as CLIS_ADDR2,
  trim(tbl.CLIS_BIRTH_DT) as CLIS_BIRTH_DT,
  trim(tbl.CLIS_CITY) as CLIS_CITY,
  trim(tbl.CLIS_CORR_PRPAY_NM) as CLIS_CORR_PRPAY_NM,
  trim(tbl.CLIS_COV_EXP_DATE) as CLIS_COV_EXP_DATE,
  trim(tbl.CLIS_FIRST_NAME) as CLIS_FIRST_NAME,
  trim(tbl.CLIS_GRGR_NAME) as CLIS_GRGR_NAME,
  trim(tbl.CLIS_LAST_NAME) as CLIS_LAST_NAME,
  trim(tbl.CLIS_LOCK_TOKEN) as CLIS_LOCK_TOKEN,
  trim(tbl.CLIS_MID_INIT) as CLIS_MID_INIT,
  trim(tbl.CLIS_OSUB_FIRST_NM) as CLIS_OSUB_FIRST_NM,
  trim(tbl.CLIS_OSUB_ID) as CLIS_OSUB_ID,
  trim(tbl.CLIS_OSUB_LAST_NM) as CLIS_OSUB_LAST_NM,
  trim(tbl.CLIS_OSUB_MID_INIT) as CLIS_OSUB_MID_INIT,
  trim(tbl.CLIS_SEX) as CLIS_SEX,
  trim(tbl.CLIS_STATE) as CLIS_STATE,
  trim(tbl.CLIS_ZIP) as CLIS_ZIP,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clis_its_subsc tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CLCL_ID),
  trim(CLIS_ADDL_DATA),
  trim(CLIS_ADDR1),
  trim(CLIS_ADDR2),
  trim(CLIS_BIRTH_DT),
  trim(CLIS_CITY),
  trim(CLIS_CORR_PRPAY_NM),
  trim(CLIS_COV_EXP_DATE),
  trim(CLIS_FIRST_NAME),
  trim(CLIS_GRGR_NAME),
  trim(CLIS_LAST_NAME),
  trim(CLIS_LOCK_TOKEN),
  trim(CLIS_MID_INIT),
  trim(CLIS_OSUB_FIRST_NM),
  trim(CLIS_OSUB_ID),
  trim(CLIS_OSUB_LAST_NM),
  trim(CLIS_OSUB_MID_INIT),
  trim(CLIS_SEX),
  trim(CLIS_STATE),
  trim(CLIS_ZIP),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_excd_expl_cd AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.EXCD_HC_ADJ_CD) as EXCD_HC_ADJ_CD,
  trim(tbl.EXCD_HC_POLICY) as EXCD_HC_POLICY,
  trim(tbl.EXCD_HC_STAT_CAT) as EXCD_HC_STAT_CAT,
  trim(tbl.EXCD_HC_STAT_CD) as EXCD_HC_STAT_CD,
  trim(tbl.EXCD_HC_STAT_CD2) as EXCD_HC_STAT_CD2,
  trim(tbl.EXCD_HC_STAT_CD3) as EXCD_HC_STAT_CD3,
  trim(tbl.EXCD_ID) as EXCD_ID,
  trim(tbl.EXCD_LOCK_TOKEN) as EXCD_LOCK_TOKEN,
  trim(tbl.EXCD_LONG_TEXT1) as EXCD_LONG_TEXT1,
  trim(tbl.EXCD_LONG_TEXT2) as EXCD_LONG_TEXT2,
  trim(tbl.EXCD_PROV_ADJ_CD) as EXCD_PROV_ADJ_CD,
  trim(tbl.EXCD_PT_LIAB_IND) as EXCD_PT_LIAB_IND,
  trim(tbl.EXCD_REMIT_REMARK) as EXCD_REMIT_REMARK,
  trim(tbl.EXCD_REMIT_REMARK2) as EXCD_REMIT_REMARK2,
  trim(tbl.EXCD_REMIT_REMARK3) as EXCD_REMIT_REMARK3,
  trim(tbl.EXCD_REMIT_REMARK4) as EXCD_REMIT_REMARK4,
  trim(tbl.EXCD_REMIT_REMARK5) as EXCD_REMIT_REMARK5,
  trim(tbl.EXCD_SHORT_TEXT) as EXCD_SHORT_TEXT,
  trim(tbl.EXCD_STS) as EXCD_STS,
  trim(tbl.EXCD_TYPE) as EXCD_TYPE,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_excd_expl_cd tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(EXCD_HC_ADJ_CD),
  trim(EXCD_HC_POLICY),
  trim(EXCD_HC_STAT_CAT),
  trim(EXCD_HC_STAT_CD),
  trim(EXCD_HC_STAT_CD2),
  trim(EXCD_HC_STAT_CD3),
  trim(EXCD_ID),
  trim(EXCD_LOCK_TOKEN),
  trim(EXCD_LONG_TEXT1),
  trim(EXCD_LONG_TEXT2),
  trim(EXCD_PROV_ADJ_CD),
  trim(EXCD_PT_LIAB_IND),
  trim(EXCD_REMIT_REMARK),
  trim(EXCD_REMIT_REMARK2),
  trim(EXCD_REMIT_REMARK3),
  trim(EXCD_REMIT_REMARK4),
  trim(EXCD_REMIT_REMARK5),
  trim(EXCD_SHORT_TEXT),
  trim(EXCD_STS),
  trim(EXCD_TYPE),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_ckck_check AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CKCK_CASHED_DT) as CKCK_CASHED_DT,
  trim(tbl.CKCK_CK_NO) as CKCK_CK_NO,
  trim(tbl.CKCK_CURR_STS) as CKCK_CURR_STS,
  trim(tbl.CKCK_LOCK_TOKEN) as CKCK_LOCK_TOKEN,
  trim(tbl.CKCK_PAYEE_NAME) as CKCK_PAYEE_NAME,
  trim(tbl.CKCK_PRINTED_DT) as CKCK_PRINTED_DT,
  trim(tbl.CKCK_REISS_DT) as CKCK_REISS_DT,
  trim(tbl.CKCK_REISS_USUS_ID) as CKCK_REISS_USUS_ID,
  trim(tbl.CKCK_SEQ_NO) as CKCK_SEQ_NO,
  trim(tbl.CKCK_TYPE) as CKCK_TYPE,
  trim(tbl.CKPY_REF_ID) as CKPY_REF_ID,
  trim(tbl.CKST_SEQ_NO) as CKST_SEQ_NO,
  trim(tbl.PYPY_ID) as PYPY_ID
FROM bronze.tbl_ckck_check tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CKCK_CASHED_DT),
  trim(CKCK_CK_NO),
  trim(CKCK_CURR_STS),
  trim(CKCK_LOCK_TOKEN),
  trim(CKCK_PAYEE_NAME),
  trim(CKCK_PRINTED_DT),
  trim(CKCK_REISS_DT),
  trim(CKCK_REISS_USUS_ID),
  trim(CKCK_SEQ_NO),
  trim(CKCK_TYPE),
  trim(CKPY_REF_ID),
  trim(CKST_SEQ_NO),
  trim(PYPY_ID);
CREATE OR REPLACE VIEW silver.V_tbl_clmd_diag_desc AS
SELECT
  
FROM bronze.tbl_clmd_diag_desc tbl
GROUP BY
  ;
CREATE OR REPLACE VIEW silver.V_tbl_ipcd_proc_cd AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.EXCD_ID) as EXCD_ID,
  trim(tbl.IPCD_ACTION) as IPCD_ACTION,
  trim(tbl.IPCD_DESC) as IPCD_DESC,
  trim(tbl.IPCD_DESC1_NVL) as IPCD_DESC1_NVL,
  trim(tbl.IPCD_DESC2_NVL) as IPCD_DESC2_NVL,
  trim(tbl.IPCD_DESC3_NVL) as IPCD_DESC3_NVL,
  trim(tbl.IPCD_EFF_DT) as IPCD_EFF_DT,
  trim(tbl.IPCD_GEN_ID_1) as IPCD_GEN_ID_1,
  trim(tbl.IPCD_GEN_ID_2) as IPCD_GEN_ID_2,
  trim(tbl.IPCD_ID) as IPCD_ID,
  trim(tbl.IPCD_LOCK_TOKEN) as IPCD_LOCK_TOKEN,
  trim(tbl.IPCD_SRCH_DISP) as IPCD_SRCH_DISP,
  trim(tbl.IPCD_TERM_DT) as IPCD_TERM_DT,
  trim(tbl.IPCD_TYPE) as IPCD_TYPE,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID,
  trim(tbl.WMDS_SEQ_NO) as WMDS_SEQ_NO
FROM bronze.tbl_ipcd_proc_cd tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(EXCD_ID),
  trim(IPCD_ACTION),
  trim(IPCD_DESC),
  trim(IPCD_DESC1_NVL),
  trim(IPCD_DESC2_NVL),
  trim(IPCD_DESC3_NVL),
  trim(IPCD_EFF_DT),
  trim(IPCD_GEN_ID_1),
  trim(IPCD_GEN_ID_2),
  trim(IPCD_ID),
  trim(IPCD_LOCK_TOKEN),
  trim(IPCD_SRCH_DISP),
  trim(IPCD_TERM_DT),
  trim(IPCD_TYPE),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID),
  trim(WMDS_SEQ_NO);
CREATE OR REPLACE VIEW silver.V_tbl_mecb_cob AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.GRGR_CK) as GRGR_CK,
  trim(tbl.MCRE_ID) as MCRE_ID,
  trim(tbl.MECB_EFF_DT) as MECB_EFF_DT,
  trim(tbl.MECB_INSUR_ORDER) as MECB_INSUR_ORDER,
  trim(tbl.MECB_INSUR_TYPE) as MECB_INSUR_TYPE,
  trim(tbl.MECB_LAST_VER_DT) as MECB_LAST_VER_DT,
  trim(tbl.MECB_LAST_VER_NAME) as MECB_LAST_VER_NAME,
  trim(tbl.MECB_LOCK_TOKEN) as MECB_LOCK_TOKEN,
  trim(tbl.MECB_LOI_START_DT) as MECB_LOI_START_DT,
  trim(tbl.MECB_MCTR_MSP) as MECB_MCTR_MSP,
  trim(tbl.MECB_MCTR_PTYP) as MECB_MCTR_PTYP,
  trim(tbl.MECB_MCTR_STYP) as MECB_MCTR_STYP,
  trim(tbl.MECB_MCTR_TRSN) as MECB_MCTR_TRSN,
  trim(tbl.MECB_MCTR_VMTH) as MECB_MCTR_VMTH,
  trim(tbl.MECB_POLICY_ID) as MECB_POLICY_ID,
  trim(tbl.MECB_PRIM_FIRST_NM) as MECB_PRIM_FIRST_NM,
  trim(tbl.MECB_PRIM_ID) as MECB_PRIM_ID,
  trim(tbl.MECB_PRIM_LAST_NM) as MECB_PRIM_LAST_NM,
  trim(tbl.MECB_RX_GROUP) as MECB_RX_GROUP,
  trim(tbl.MECB_RX_ID) as MECB_RX_ID,
  trim(tbl.MECB_RXBIN) as MECB_RXBIN,
  trim(tbl.MECB_RXPCN) as MECB_RXPCN,
  trim(tbl.MECB_TERM_DT) as MECB_TERM_DT,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_mecb_cob tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(GRGR_CK),
  trim(MCRE_ID),
  trim(MECB_EFF_DT),
  trim(MECB_INSUR_ORDER),
  trim(MECB_INSUR_TYPE),
  trim(MECB_LAST_VER_DT),
  trim(MECB_LAST_VER_NAME),
  trim(MECB_LOCK_TOKEN),
  trim(MECB_LOI_START_DT),
  trim(MECB_MCTR_MSP),
  trim(MECB_MCTR_PTYP),
  trim(MECB_MCTR_STYP),
  trim(MECB_MCTR_TRSN),
  trim(MECB_MCTR_VMTH),
  trim(MECB_POLICY_ID),
  trim(MECB_PRIM_FIRST_NM),
  trim(MECB_PRIM_ID),
  trim(MECB_PRIM_LAST_NM),
  trim(MECB_RX_GROUP),
  trim(MECB_RX_ID),
  trim(MECB_RXBIN),
  trim(MECB_RXPCN),
  trim(MECB_TERM_DT),
  trim(MEME_CK),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_cdml_cl_line AS
SELECT
  trim(tbl.APCD_ID) as APCD_ID,
  trim(tbl.APSI_STS_IND) as APSI_STS_IND,
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CDML_AG_PRICE) as CDML_AG_PRICE,
  trim(tbl.CDML_ALLOW) as CDML_ALLOW,
  trim(tbl.CDML_ANES_PHY_STAT) as CDML_ANES_PHY_STAT,
  trim(tbl.CDML_AUTHSV_SEQ_NO) as CDML_AUTHSV_SEQ_NO,
  trim(tbl.CDML_CAP_IND) as CDML_CAP_IND,
  trim(tbl.CDML_CHG_AMT) as CDML_CHG_AMT,
  trim(tbl.CDML_CL_NTWK_IND) as CDML_CL_NTWK_IND,
  trim(tbl.CDML_CLMD_TYPE2) as CDML_CLMD_TYPE2,
  trim(tbl.CDML_CLMD_TYPE3) as CDML_CLMD_TYPE3,
  trim(tbl.CDML_CLMD_TYPE4) as CDML_CLMD_TYPE4,
  trim(tbl.CDML_CLMD_TYPE5) as CDML_CLMD_TYPE5,
  trim(tbl.CDML_CLMD_TYPE6) as CDML_CLMD_TYPE6,
  trim(tbl.CDML_CLMD_TYPE7) as CDML_CLMD_TYPE7,
  trim(tbl.CDML_CLMD_TYPE8) as CDML_CLMD_TYPE8,
  trim(tbl.CDML_COINS_AMT) as CDML_COINS_AMT,
  trim(tbl.CDML_CONSIDER_CHG) as CDML_CONSIDER_CHG,
  trim(tbl.CDML_COPAY_AMT) as CDML_COPAY_AMT,
  trim(tbl.CDML_CUR_STS) as CDML_CUR_STS,
  trim(tbl.CDML_DED_ACC_NO) as CDML_DED_ACC_NO,
  trim(tbl.CDML_DED_AMT) as CDML_DED_AMT,
  trim(tbl.CDML_DIS_PA_LIAB) as CDML_DIS_PA_LIAB,
  trim(tbl.CDML_DISALL_AMT) as CDML_DISALL_AMT,
  trim(tbl.CDML_DISALL_EXCD) as CDML_DISALL_EXCD,
  trim(tbl.CDML_DISC_AMT) as CDML_DISC_AMT,
  trim(tbl.CDML_EOB_EXCD) as CDML_EOB_EXCD,
  trim(tbl.CDML_EXT_LINE_NO) as CDML_EXT_LINE_NO,
  trim(tbl.CDML_FROM_DT) as CDML_FROM_DT,
  trim(tbl.CDML_GWID) as CDML_GWID,
  trim(tbl.CDML_HCPCS_AMT) as CDML_HCPCS_AMT,
  trim(tbl.CDML_IP_PRICE) as CDML_IP_PRICE,
  trim(tbl.CDML_IPCD_MOD2) as CDML_IPCD_MOD2,
  trim(tbl.CDML_IPCD_MOD3) as CDML_IPCD_MOD3,
  trim(tbl.CDML_IPCD_MOD4) as CDML_IPCD_MOD4,
  trim(tbl.CDML_ITS_DISC_AMT) as CDML_ITS_DISC_AMT,
  trim(tbl.CDML_LOCK_TOKEN) as CDML_LOCK_TOKEN,
  trim(tbl.CDML_MU_EDIT_IND) as CDML_MU_EDIT_IND,
  trim(tbl.CDML_OOP_CALC_BASE) as CDML_OOP_CALC_BASE,
  trim(tbl.CDML_PAID_AMT) as CDML_PAID_AMT,
  trim(tbl.CDML_PC_IND) as CDML_PC_IND,
  trim(tbl.CDML_PF_PRICE) as CDML_PF_PRICE,
  trim(tbl.CDML_PGPD_DISC_AMT_NVL) as CDML_PGPD_DISC_AMT_NVL,
  trim(tbl.CDML_PGPD_EXCD_ID) as CDML_PGPD_EXCD_ID,
  trim(tbl.CDML_PGPW_EXCD_ID) as CDML_PGPW_EXCD_ID,
  trim(tbl.CDML_PGPW_WHLD_AMT_NVL) as CDML_PGPW_WHLD_AMT_NVL,
  trim(tbl.CDML_POS_IND) as CDML_POS_IND,
  trim(tbl.CDML_PR_LN_CNTL_NO_NVL) as CDML_PR_LN_CNTL_NO_NVL,
  trim(tbl.CDML_PR_PYMT_AMT) as CDML_PR_PYMT_AMT,
  trim(tbl.CDML_PRE_AUTH_IND) as CDML_PRE_AUTH_IND,
  trim(tbl.CDML_PRE_PAID_AMT) as CDML_PRE_PAID_AMT,
  trim(tbl.CDML_PRICE_IND) as CDML_PRICE_IND,
  trim(tbl.CDML_REF_IND) as CDML_REF_IND,
  trim(tbl.CDML_REFSV_SEQ_NO) as CDML_REFSV_SEQ_NO,
  trim(tbl.CDML_RISK_WH_AMT) as CDML_RISK_WH_AMT,
  trim(tbl.CDML_ROOM_TYPE) as CDML_ROOM_TYPE,
  trim(tbl.CDML_SB_PYMT_AMT) as CDML_SB_PYMT_AMT,
  trim(tbl.CDML_SE_PRICE) as CDML_SE_PRICE,
  trim(tbl.CDML_SEPY_ACCT_CAT) as CDML_SEPY_ACCT_CAT,
  trim(tbl.CDML_SEPY_EXP_CAT) as CDML_SEPY_EXP_CAT,
  trim(tbl.CDML_SEQ_NO) as CDML_SEQ_NO,
  trim(tbl.CDML_SEQUEST_AMT_NVL) as CDML_SEQUEST_AMT_NVL,
  trim(tbl.CDML_SEQUEST_EXCD_NVL) as CDML_SEQUEST_EXCD_NVL,
  trim(tbl.CDML_SUP_DISC_AMT) as CDML_SUP_DISC_AMT,
  trim(tbl.CDML_TO_DT) as CDML_TO_DT,
  trim(tbl.CDML_TOT_PA_LIAB) as CDML_TOT_PA_LIAB,
  trim(tbl.CDML_UARR_RULE_ID_NVL) as CDML_UARR_RULE_ID_NVL,
  trim(tbl.CDML_UMAUTH_ID) as CDML_UMAUTH_ID,
  trim(tbl.CDML_UMPG_ID_NVL) as CDML_UMPG_ID_NVL,
  trim(tbl.CDML_UMREF_ID) as CDML_UMREF_ID,
  trim(tbl.CDML_UNITS) as CDML_UNITS,
  trim(tbl.CDML_UNITS_ALLOW) as CDML_UNITS_ALLOW,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CRFD_FUND_ID) as CRFD_FUND_ID,
  trim(tbl.CRPL_POOL_ID) as CRPL_POOL_ID,
  trim(tbl.DEDE_PFX) as DEDE_PFX,
  trim(tbl.EHBD_ID_NVL) as EHBD_ID_NVL,
  trim(tbl.IDCD_ID) as IDCD_ID,
  trim(tbl.IDCD_ID_CNV_NVL) as IDCD_ID_CNV_NVL,
  trim(tbl.IDCD_ID_REL) as IDCD_ID_REL,
  trim(tbl.IDCD_ID_SUB) as IDCD_ID_SUB,
  trim(tbl.IDCD_ID_SUB_REL) as IDCD_ID_SUB_REL,
  trim(tbl.IDCD_ID_TRANS) as IDCD_ID_TRANS,
  trim(tbl.IDCD_ID_TRANS_REL) as IDCD_ID_TRANS_REL,
  trim(tbl.IPCD_ID) as IPCD_ID,
  trim(tbl.LOBD_ID) as LOBD_ID,
  trim(tbl.LTLT_PFX) as LTLT_PFX,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.PDVC_LOBD_PTR) as PDVC_LOBD_PTR,
  trim(tbl.PGPD_PFX) as PGPD_PFX,
  trim(tbl.PGPW_PFX) as PGPW_PFX,
  trim(tbl.PRCF_MCTR_SPEC) as PRCF_MCTR_SPEC,
  trim(tbl.PRPR_ID) as PRPR_ID,
  trim(tbl.PSCD_ID) as PSCD_ID,
  trim(tbl.RCRC_ID) as RCRC_ID,
  trim(tbl.RPTC_RPT_CAT) as RPTC_RPT_CAT,
  trim(tbl.SEPC_PRICE_ID) as SEPC_PRICE_ID,
  trim(tbl.SEPY_PFX) as SEPY_PFX,
  trim(tbl.SESE_ID) as SESE_ID,
  trim(tbl.SESE_RULE) as SESE_RULE
FROM bronze.tbl_cdml_cl_line tbl
GROUP BY
  trim(APCD_ID),
  trim(APSI_STS_IND),
  trim(ATXR_SOURCE_ID),
  trim(CDML_AG_PRICE),
  trim(CDML_ALLOW),
  trim(CDML_ANES_PHY_STAT),
  trim(CDML_AUTHSV_SEQ_NO),
  trim(CDML_CAP_IND),
  trim(CDML_CHG_AMT),
  trim(CDML_CL_NTWK_IND),
  trim(CDML_CLMD_TYPE2),
  trim(CDML_CLMD_TYPE3),
  trim(CDML_CLMD_TYPE4),
  trim(CDML_CLMD_TYPE5),
  trim(CDML_CLMD_TYPE6),
  trim(CDML_CLMD_TYPE7),
  trim(CDML_CLMD_TYPE8),
  trim(CDML_COINS_AMT),
  trim(CDML_CONSIDER_CHG),
  trim(CDML_COPAY_AMT),
  trim(CDML_CUR_STS),
  trim(CDML_DED_ACC_NO),
  trim(CDML_DED_AMT),
  trim(CDML_DIS_PA_LIAB),
  trim(CDML_DISALL_AMT),
  trim(CDML_DISALL_EXCD),
  trim(CDML_DISC_AMT),
  trim(CDML_EOB_EXCD),
  trim(CDML_EXT_LINE_NO),
  trim(CDML_FROM_DT),
  trim(CDML_GWID),
  trim(CDML_HCPCS_AMT),
  trim(CDML_IP_PRICE),
  trim(CDML_IPCD_MOD2),
  trim(CDML_IPCD_MOD3),
  trim(CDML_IPCD_MOD4),
  trim(CDML_ITS_DISC_AMT),
  trim(CDML_LOCK_TOKEN),
  trim(CDML_MU_EDIT_IND),
  trim(CDML_OOP_CALC_BASE),
  trim(CDML_PAID_AMT),
  trim(CDML_PC_IND),
  trim(CDML_PF_PRICE),
  trim(CDML_PGPD_DISC_AMT_NVL),
  trim(CDML_PGPD_EXCD_ID),
  trim(CDML_PGPW_EXCD_ID),
  trim(CDML_PGPW_WHLD_AMT_NVL),
  trim(CDML_POS_IND),
  trim(CDML_PR_LN_CNTL_NO_NVL),
  trim(CDML_PR_PYMT_AMT),
  trim(CDML_PRE_AUTH_IND),
  trim(CDML_PRE_PAID_AMT),
  trim(CDML_PRICE_IND),
  trim(CDML_REF_IND),
  trim(CDML_REFSV_SEQ_NO),
  trim(CDML_RISK_WH_AMT),
  trim(CDML_ROOM_TYPE),
  trim(CDML_SB_PYMT_AMT),
  trim(CDML_SE_PRICE),
  trim(CDML_SEPY_ACCT_CAT),
  trim(CDML_SEPY_EXP_CAT),
  trim(CDML_SEQ_NO),
  trim(CDML_SEQUEST_AMT_NVL),
  trim(CDML_SEQUEST_EXCD_NVL),
  trim(CDML_SUP_DISC_AMT),
  trim(CDML_TO_DT),
  trim(CDML_TOT_PA_LIAB),
  trim(CDML_UARR_RULE_ID_NVL),
  trim(CDML_UMAUTH_ID),
  trim(CDML_UMPG_ID_NVL),
  trim(CDML_UMREF_ID),
  trim(CDML_UNITS),
  trim(CDML_UNITS_ALLOW),
  trim(CLCL_ID),
  trim(CRFD_FUND_ID),
  trim(CRPL_POOL_ID),
  trim(DEDE_PFX),
  trim(EHBD_ID_NVL),
  trim(IDCD_ID),
  trim(IDCD_ID_CNV_NVL),
  trim(IDCD_ID_REL),
  trim(IDCD_ID_SUB),
  trim(IDCD_ID_SUB_REL),
  trim(IDCD_ID_TRANS),
  trim(IDCD_ID_TRANS_REL),
  trim(IPCD_ID),
  trim(LOBD_ID),
  trim(LTLT_PFX),
  trim(MEME_CK),
  trim(PDVC_LOBD_PTR),
  trim(PGPD_PFX),
  trim(PGPW_PFX),
  trim(PRCF_MCTR_SPEC),
  trim(PRPR_ID),
  trim(PSCD_ID),
  trim(RCRC_ID),
  trim(RPTC_RPT_CAT),
  trim(SEPC_PRICE_ID),
  trim(SEPY_PFX),
  trim(SESE_ID),
  trim(SESE_RULE);
CREATE OR REPLACE VIEW silver.V_tbl_pypy_payor AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.PYBA_ID) as PYBA_ID,
  trim(tbl.PYPY_835_ACH_FMT) as PYPY_835_ACH_FMT,
  trim(tbl.PYPY_835_PAY_METH) as PYPY_835_PAY_METH,
  trim(tbl.PYPY_ADDR1) as PYPY_ADDR1,
  trim(tbl.PYPY_ADDR2) as PYPY_ADDR2,
  trim(tbl.PYPY_ADDR3) as PYPY_ADDR3,
  trim(tbl.PYPY_BC_EMAIL) as PYPY_BC_EMAIL,
  trim(tbl.PYPY_BC_FAX) as PYPY_BC_FAX,
  trim(tbl.PYPY_BC_NAME) as PYPY_BC_NAME,
  trim(tbl.PYPY_BC_PHONE) as PYPY_BC_PHONE,
  trim(tbl.PYPY_BC_PHONE_EXT) as PYPY_BC_PHONE_EXT,
  trim(tbl.PYPY_CITY) as PYPY_CITY,
  trim(tbl.PYPY_CK_STOCK) as PYPY_CK_STOCK,
  trim(tbl.PYPY_COUNTY) as PYPY_COUNTY,
  trim(tbl.PYPY_CTRY_CD) as PYPY_CTRY_CD,
  trim(tbl.PYPY_DFI_ID_QUAL) as PYPY_DFI_ID_QUAL,
  trim(tbl.PYPY_EDI_835_IND) as PYPY_EDI_835_IND,
  trim(tbl.PYPY_EDI_DEST_ID) as PYPY_EDI_DEST_ID,
  trim(tbl.PYPY_EDI_DEST_QUAL) as PYPY_EDI_DEST_QUAL,
  trim(tbl.PYPY_EFF_DT) as PYPY_EFF_DT,
  trim(tbl.PYPY_EMAIL) as PYPY_EMAIL,
  trim(tbl.PYPY_FAX) as PYPY_FAX,
  trim(tbl.PYPY_FAX_EXT) as PYPY_FAX_EXT,
  trim(tbl.PYPY_HLTH_IND_NO) as PYPY_HLTH_IND_NO,
  trim(tbl.PYPY_ID) as PYPY_ID,
  trim(tbl.PYPY_ID_NO) as PYPY_ID_NO,
  trim(tbl.PYPY_LASER_CK_IND) as PYPY_LASER_CK_IND,
  trim(tbl.PYPY_LOCK_TOKEN) as PYPY_LOCK_TOKEN,
  trim(tbl.PYPY_NAIC_CODE) as PYPY_NAIC_CODE,
  trim(tbl.PYPY_NATL_PLAN_ID) as PYPY_NATL_PLAN_ID,
  trim(tbl.PYPY_PAYOR_NAME) as PYPY_PAYOR_NAME,
  trim(tbl.PYPY_PHONE) as PYPY_PHONE,
  trim(tbl.PYPY_PHONE_EXT) as PYPY_PHONE_EXT,
  trim(tbl.PYPY_STATE) as PYPY_STATE,
  trim(tbl.PYPY_TAX_ID) as PYPY_TAX_ID,
  trim(tbl.PYPY_TC_EMAIL) as PYPY_TC_EMAIL,
  trim(tbl.PYPY_TC_FAX) as PYPY_TC_FAX,
  trim(tbl.PYPY_TC_NAME) as PYPY_TC_NAME,
  trim(tbl.PYPY_TC_PHONE) as PYPY_TC_PHONE,
  trim(tbl.PYPY_TC_PHONE_EXT) as PYPY_TC_PHONE_EXT,
  trim(tbl.PYPY_TC_WEBSITE) as PYPY_TC_WEBSITE,
  trim(tbl.PYPY_TERM_DT) as PYPY_TERM_DT,
  trim(tbl.PYPY_WEBSITE) as PYPY_WEBSITE,
  trim(tbl.PYPY_ZIP) as PYPY_ZIP,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_pypy_payor tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(PYBA_ID),
  trim(PYPY_835_ACH_FMT),
  trim(PYPY_835_PAY_METH),
  trim(PYPY_ADDR1),
  trim(PYPY_ADDR2),
  trim(PYPY_ADDR3),
  trim(PYPY_BC_EMAIL),
  trim(PYPY_BC_FAX),
  trim(PYPY_BC_NAME),
  trim(PYPY_BC_PHONE),
  trim(PYPY_BC_PHONE_EXT),
  trim(PYPY_CITY),
  trim(PYPY_CK_STOCK),
  trim(PYPY_COUNTY),
  trim(PYPY_CTRY_CD),
  trim(PYPY_DFI_ID_QUAL),
  trim(PYPY_EDI_835_IND),
  trim(PYPY_EDI_DEST_ID),
  trim(PYPY_EDI_DEST_QUAL),
  trim(PYPY_EFF_DT),
  trim(PYPY_EMAIL),
  trim(PYPY_FAX),
  trim(PYPY_FAX_EXT),
  trim(PYPY_HLTH_IND_NO),
  trim(PYPY_ID),
  trim(PYPY_ID_NO),
  trim(PYPY_LASER_CK_IND),
  trim(PYPY_LOCK_TOKEN),
  trim(PYPY_NAIC_CODE),
  trim(PYPY_NATL_PLAN_ID),
  trim(PYPY_PAYOR_NAME),
  trim(PYPY_PHONE),
  trim(PYPY_PHONE_EXT),
  trim(PYPY_STATE),
  trim(PYPY_TAX_ID),
  trim(PYPY_TC_EMAIL),
  trim(PYPY_TC_FAX),
  trim(PYPY_TC_NAME),
  trim(PYPY_TC_PHONE),
  trim(PYPY_TC_PHONE_EXT),
  trim(PYPY_TC_WEBSITE),
  trim(PYPY_TERM_DT),
  trim(PYPY_WEBSITE),
  trim(PYPY_ZIP),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_mepr_prim_prov AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.GRGR_CK) as GRGR_CK,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.MEPR_CAP_REL_ENT) as MEPR_CAP_REL_ENT,
  trim(tbl.MEPR_CR_EFF_DT) as MEPR_CR_EFF_DT,
  trim(tbl.MEPR_CR_TERM_DT) as MEPR_CR_TERM_DT,
  trim(tbl.MEPR_DEMGRPHC_IND) as MEPR_DEMGRPHC_IND,
  trim(tbl.MEPR_EFF_DT) as MEPR_EFF_DT,
  trim(tbl.MEPR_LOCK_TOKEN) as MEPR_LOCK_TOKEN,
  trim(tbl.MEPR_MCTR_ERSN) as MEPR_MCTR_ERSN,
  trim(tbl.MEPR_MCTR_ORSN) as MEPR_MCTR_ORSN,
  trim(tbl.MEPR_MCTR_TRSN) as MEPR_MCTR_TRSN,
  trim(tbl.MEPR_PCP_TYPE) as MEPR_PCP_TYPE,
  trim(tbl.MEPR_SOURCE) as MEPR_SOURCE,
  trim(tbl.MEPR_SOURCE_DT_NVL) as MEPR_SOURCE_DT_NVL,
  trim(tbl.MEPR_TERM_DT) as MEPR_TERM_DT,
  trim(tbl.PDPD_CAP_RET_MOS) as PDPD_CAP_RET_MOS,
  trim(tbl.PRPR_ID) as PRPR_ID,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_mepr_prim_prov tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(GRGR_CK),
  trim(MEME_CK),
  trim(MEPR_CAP_REL_ENT),
  trim(MEPR_CR_EFF_DT),
  trim(MEPR_CR_TERM_DT),
  trim(MEPR_DEMGRPHC_IND),
  trim(MEPR_EFF_DT),
  trim(MEPR_LOCK_TOKEN),
  trim(MEPR_MCTR_ERSN),
  trim(MEPR_MCTR_ORSN),
  trim(MEPR_MCTR_TRSN),
  trim(MEPR_PCP_TYPE),
  trim(MEPR_SOURCE),
  trim(MEPR_SOURCE_DT_NVL),
  trim(MEPR_TERM_DT),
  trim(PDPD_CAP_RET_MOS),
  trim(PRPR_ID),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_plds_plan_desc AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CSPI_ID) as CSPI_ID,
  trim(tbl.PLDS_DESC) as PLDS_DESC,
  trim(tbl.PLDS_LOCK_TOKEN) as PLDS_LOCK_TOKEN,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_plds_plan_desc tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CSPI_ID),
  trim(PLDS_DESC),
  trim(PLDS_LOCK_TOKEN),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_clck_clm_check AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CKPY_PAY_DT) as CKPY_PAY_DT,
  trim(tbl.CKPY_REF_ID) as CKPY_REF_ID,
  trim(tbl.CLCK_AGPP_EXCD_ID) as CLCK_AGPP_EXCD_ID,
  trim(tbl.CLCK_ALLOW) as CLCK_ALLOW,
  trim(tbl.CLCK_CALC_INT_AMT) as CLCK_CALC_INT_AMT,
  trim(tbl.CLCK_COMB_IND) as CLCK_COMB_IND,
  trim(tbl.CLCK_DISC_PCT) as CLCK_DISC_PCT,
  trim(tbl.CLCK_EOB_IND) as CLCK_EOB_IND,
  trim(tbl.CLCK_EXT_MOD_IND_NVL) as CLCK_EXT_MOD_IND_NVL,
  trim(tbl.CLCK_HSA_ORIG_AMT) as CLCK_HSA_ORIG_AMT,
  trim(tbl.CLCK_HSA_PRIOR_PD) as CLCK_HSA_PRIOR_PD,
  trim(tbl.CLCK_INT_AMT) as CLCK_INT_AMT,
  trim(tbl.CLCK_LOCK_TOKEN) as CLCK_LOCK_TOKEN,
  trim(tbl.CLCK_NET_AMT) as CLCK_NET_AMT,
  trim(tbl.CLCK_NTWK_IND) as CLCK_NTWK_IND,
  trim(tbl.CLCK_ORIG_AMT) as CLCK_ORIG_AMT,
  trim(tbl.CLCK_PAYEE_IND) as CLCK_PAYEE_IND,
  trim(tbl.CLCK_PAYEE_PR_ID) as CLCK_PAYEE_PR_ID,
  trim(tbl.CLCK_PR_INT_OVR_PD_NVL) as CLCK_PR_INT_OVR_PD_NVL,
  trim(tbl.CLCK_PR_ORIG_AMT_NVL) as CLCK_PR_ORIG_AMT_NVL,
  trim(tbl.CLCK_PR_PRIOR_PD_NVL) as CLCK_PR_PRIOR_PD_NVL,
  trim(tbl.CLCK_PRIOR_PD) as CLCK_PRIOR_PD,
  trim(tbl.CLCK_PRM_INT_AMT_NVL) as CLCK_PRM_INT_AMT_NVL,
  trim(tbl.CLCK_PRM_INT_CALC_NVL) as CLCK_PRM_INT_CALC_NVL,
  trim(tbl.CLCK_PROM_PAY_DISC) as CLCK_PROM_PAY_DISC,
  trim(tbl.CLCK_PYMT_OVRD_IND) as CLCK_PYMT_OVRD_IND,
  trim(tbl.CLCK_SC_INT_AMT_NVL) as CLCK_SC_INT_AMT_NVL,
  trim(tbl.CLCK_SC_INT_CALC_NVL) as CLCK_SC_INT_CALC_NVL,
  trim(tbl.CLCK_SC_INT_OVR_PD_NVL) as CLCK_SC_INT_OVR_PD_NVL,
  trim(tbl.CLCK_SC_ORIG_AMT_NVL) as CLCK_SC_ORIG_AMT_NVL,
  trim(tbl.CLCK_SC_PRIOR_PD_NVL) as CLCK_SC_PRIOR_PD_NVL,
  trim(tbl.CLCK_TRNS_SOURC_NVL) as CLCK_TRNS_SOURC_NVL,
  trim(tbl.CLCK_UM_VIOL_IND) as CLCK_UM_VIOL_IND,
  trim(tbl.CLCL_CL_SUB_TYPE) as CLCL_CL_SUB_TYPE,
  trim(tbl.CLCL_CL_TYPE) as CLCL_CL_TYPE,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.LOBD_ID) as LOBD_ID,
  trim(tbl.MEDA_CONFID_IND) as MEDA_CONFID_IND,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.PRPR_ID) as PRPR_ID,
  trim(tbl.SBSB_CK) as SBSB_CK
FROM bronze.tbl_clck_clm_check tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CKPY_PAY_DT),
  trim(CKPY_REF_ID),
  trim(CLCK_AGPP_EXCD_ID),
  trim(CLCK_ALLOW),
  trim(CLCK_CALC_INT_AMT),
  trim(CLCK_COMB_IND),
  trim(CLCK_DISC_PCT),
  trim(CLCK_EOB_IND),
  trim(CLCK_EXT_MOD_IND_NVL),
  trim(CLCK_HSA_ORIG_AMT),
  trim(CLCK_HSA_PRIOR_PD),
  trim(CLCK_INT_AMT),
  trim(CLCK_LOCK_TOKEN),
  trim(CLCK_NET_AMT),
  trim(CLCK_NTWK_IND),
  trim(CLCK_ORIG_AMT),
  trim(CLCK_PAYEE_IND),
  trim(CLCK_PAYEE_PR_ID),
  trim(CLCK_PR_INT_OVR_PD_NVL),
  trim(CLCK_PR_ORIG_AMT_NVL),
  trim(CLCK_PR_PRIOR_PD_NVL),
  trim(CLCK_PRIOR_PD),
  trim(CLCK_PRM_INT_AMT_NVL),
  trim(CLCK_PRM_INT_CALC_NVL),
  trim(CLCK_PROM_PAY_DISC),
  trim(CLCK_PYMT_OVRD_IND),
  trim(CLCK_SC_INT_AMT_NVL),
  trim(CLCK_SC_INT_CALC_NVL),
  trim(CLCK_SC_INT_OVR_PD_NVL),
  trim(CLCK_SC_ORIG_AMT_NVL),
  trim(CLCK_SC_PRIOR_PD_NVL),
  trim(CLCK_TRNS_SOURC_NVL),
  trim(CLCK_UM_VIOL_IND),
  trim(CLCL_CL_SUB_TYPE),
  trim(CLCL_CL_TYPE),
  trim(CLCL_ID),
  trim(LOBD_ID),
  trim(MEDA_CONFID_IND),
  trim(MEME_CK),
  trim(PRPR_ID),
  trim(SBSB_CK);
CREATE OR REPLACE VIEW silver.V_tbl_lobd_line_bus AS
SELECT
  trim(tbl.ACPE_ID) as ACPE_ID,
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.LOBD_ADDR1) as LOBD_ADDR1,
  trim(tbl.LOBD_ADDR2) as LOBD_ADDR2,
  trim(tbl.LOBD_ADDR3) as LOBD_ADDR3,
  trim(tbl.LOBD_CITY) as LOBD_CITY,
  trim(tbl.LOBD_CO_RED_IND) as LOBD_CO_RED_IND,
  trim(tbl.LOBD_COUNTY) as LOBD_COUNTY,
  trim(tbl.LOBD_CR_RED_IND) as LOBD_CR_RED_IND,
  trim(tbl.LOBD_CTRY_CD) as LOBD_CTRY_CD,
  trim(tbl.LOBD_DIS_RED_IND) as LOBD_DIS_RED_IND,
  trim(tbl.LOBD_EMAIL) as LOBD_EMAIL,
  trim(tbl.LOBD_EOB_COPY_IND) as LOBD_EOB_COPY_IND,
  trim(tbl.LOBD_FAX) as LOBD_FAX,
  trim(tbl.LOBD_FAX_EXT) as LOBD_FAX_EXT,
  trim(tbl.LOBD_FSA_RED_IND) as LOBD_FSA_RED_IND,
  trim(tbl.LOBD_ID) as LOBD_ID,
  trim(tbl.LOBD_ID_COMM) as LOBD_ID_COMM,
  trim(tbl.LOBD_LOCK_TOKEN) as LOBD_LOCK_TOKEN,
  trim(tbl.LOBD_MCTR_TYPE) as LOBD_MCTR_TYPE,
  trim(tbl.LOBD_NAME) as LOBD_NAME,
  trim(tbl.LOBD_OVP_EXCD_ID) as LOBD_OVP_EXCD_ID,
  trim(tbl.LOBD_PAY_CL_METH) as LOBD_PAY_CL_METH,
  trim(tbl.LOBD_PAY_DIS_METH) as LOBD_PAY_DIS_METH,
  trim(tbl.LOBD_PAY_FSAC_METH) as LOBD_PAY_FSAC_METH,
  trim(tbl.LOBD_PAY_VIS_METH) as LOBD_PAY_VIS_METH,
  trim(tbl.LOBD_PHONE) as LOBD_PHONE,
  trim(tbl.LOBD_PHONE_EXT) as LOBD_PHONE_EXT,
  trim(tbl.LOBD_PR_RED_IND) as LOBD_PR_RED_IND,
  trim(tbl.LOBD_SB_RED_IND) as LOBD_SB_RED_IND,
  trim(tbl.LOBD_STATE) as LOBD_STATE,
  trim(tbl.LOBD_VIS_RED_IND) as LOBD_VIS_RED_IND,
  trim(tbl.LOBD_ZIP) as LOBD_ZIP,
  trim(tbl.PYPY_ID) as PYPY_ID,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_lobd_line_bus tbl
GROUP BY
  trim(ACPE_ID),
  trim(ATXR_SOURCE_ID),
  trim(LOBD_ADDR1),
  trim(LOBD_ADDR2),
  trim(LOBD_ADDR3),
  trim(LOBD_CITY),
  trim(LOBD_CO_RED_IND),
  trim(LOBD_COUNTY),
  trim(LOBD_CR_RED_IND),
  trim(LOBD_CTRY_CD),
  trim(LOBD_DIS_RED_IND),
  trim(LOBD_EMAIL),
  trim(LOBD_EOB_COPY_IND),
  trim(LOBD_FAX),
  trim(LOBD_FAX_EXT),
  trim(LOBD_FSA_RED_IND),
  trim(LOBD_ID),
  trim(LOBD_ID_COMM),
  trim(LOBD_LOCK_TOKEN),
  trim(LOBD_MCTR_TYPE),
  trim(LOBD_NAME),
  trim(LOBD_OVP_EXCD_ID),
  trim(LOBD_PAY_CL_METH),
  trim(LOBD_PAY_DIS_METH),
  trim(LOBD_PAY_FSAC_METH),
  trim(LOBD_PAY_VIS_METH),
  trim(LOBD_PHONE),
  trim(LOBD_PHONE_EXT),
  trim(LOBD_PR_RED_IND),
  trim(LOBD_SB_RED_IND),
  trim(LOBD_STATE),
  trim(LOBD_VIS_RED_IND),
  trim(LOBD_ZIP),
  trim(PYPY_ID),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_pdpd_product AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.LOBD_ALT_RISK_ID) as LOBD_ALT_RISK_ID,
  trim(tbl.LOBD_ID) as LOBD_ID,
  trim(tbl.PDPD_ACC_SFX) as PDPD_ACC_SFX,
  trim(tbl.PDPD_ACC_SHDW_SFX_NVL) as PDPD_ACC_SHDW_SFX_NVL,
  trim(tbl.PDPD_CAP_POP_LVL) as PDPD_CAP_POP_LVL,
  trim(tbl.PDPD_CAP_RET_MOS) as PDPD_CAP_RET_MOS,
  trim(tbl.PDPD_EFF_DT) as PDPD_EFF_DT,
  trim(tbl.PDPD_ID) as PDPD_ID,
  trim(tbl.PDPD_LOCK_TOKEN) as PDPD_LOCK_TOKEN,
  trim(tbl.PDPD_MCTR_CCAT) as PDPD_MCTR_CCAT,
  trim(tbl.PDPD_OPTS) as PDPD_OPTS,
  trim(tbl.PDPD_RISK_IND) as PDPD_RISK_IND,
  trim(tbl.PDPD_TERM_DT) as PDPD_TERM_DT,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_pdpd_product tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(LOBD_ALT_RISK_ID),
  trim(LOBD_ID),
  trim(PDPD_ACC_SFX),
  trim(PDPD_ACC_SHDW_SFX_NVL),
  trim(PDPD_CAP_POP_LVL),
  trim(PDPD_CAP_RET_MOS),
  trim(PDPD_EFF_DT),
  trim(PDPD_ID),
  trim(PDPD_LOCK_TOKEN),
  trim(PDPD_MCTR_CCAT),
  trim(PDPD_OPTS),
  trim(PDPD_RISK_IND),
  trim(PDPD_TERM_DT),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_idcd_diag_cd AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.EXCD_ID) as EXCD_ID,
  trim(tbl.IDCD_ACTION) as IDCD_ACTION,
  trim(tbl.IDCD_DESC) as IDCD_DESC,
  trim(tbl.IDCD_EFF_DT) as IDCD_EFF_DT,
  trim(tbl.IDCD_GEN_ID_1) as IDCD_GEN_ID_1,
  trim(tbl.IDCD_GEN_ID_2) as IDCD_GEN_ID_2,
  trim(tbl.IDCD_ID) as IDCD_ID,
  trim(tbl.IDCD_ID_REL) as IDCD_ID_REL,
  trim(tbl.IDCD_LOCK_TOKEN) as IDCD_LOCK_TOKEN,
  trim(tbl.IDCD_OPL_IND) as IDCD_OPL_IND,
  trim(tbl.IDCD_TERM_DT) as IDCD_TERM_DT,
  trim(tbl.IDCD_TYPE) as IDCD_TYPE,
  trim(tbl.MDCD_ID_F) as MDCD_ID_F,
  trim(tbl.MDCD_ID_M) as MDCD_ID_M,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID,
  trim(tbl.TPCT_MCTR_TCAT) as TPCT_MCTR_TCAT
FROM bronze.tbl_idcd_diag_cd tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(EXCD_ID),
  trim(IDCD_ACTION),
  trim(IDCD_DESC),
  trim(IDCD_EFF_DT),
  trim(IDCD_GEN_ID_1),
  trim(IDCD_GEN_ID_2),
  trim(IDCD_ID),
  trim(IDCD_ID_REL),
  trim(IDCD_LOCK_TOKEN),
  trim(IDCD_OPL_IND),
  trim(IDCD_TERM_DT),
  trim(IDCD_TYPE),
  trim(MDCD_ID_F),
  trim(MDCD_ID_M),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID),
  trim(TPCT_MCTR_TCAT);
CREATE OR REPLACE VIEW silver.V_tbl_prad_address AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.PRAD_ADDR1) as PRAD_ADDR1,
  trim(tbl.PRAD_ADDR2) as PRAD_ADDR2,
  trim(tbl.PRAD_ADDR3) as PRAD_ADDR3,
  trim(tbl.PRAD_CITY) as PRAD_CITY,
  trim(tbl.PRAD_CITY_XLOW) as PRAD_CITY_XLOW,
  trim(tbl.PRAD_COUNTY) as PRAD_COUNTY,
  trim(tbl.PRAD_CTRY_CD) as PRAD_CTRY_CD,
  trim(tbl.PRAD_DIRECTORY_IND) as PRAD_DIRECTORY_IND,
  trim(tbl.PRAD_EFF_DT) as PRAD_EFF_DT,
  trim(tbl.PRAD_EMAIL) as PRAD_EMAIL,
  trim(tbl.PRAD_FAX) as PRAD_FAX,
  trim(tbl.PRAD_FAX_EXT) as PRAD_FAX_EXT,
  trim(tbl.PRAD_GEO_RTRN_CD) as PRAD_GEO_RTRN_CD,
  trim(tbl.PRAD_HD_IND) as PRAD_HD_IND,
  trim(tbl.PRAD_ID) as PRAD_ID,
  trim(tbl.PRAD_LAT) as PRAD_LAT,
  trim(tbl.PRAD_LOCK_TOKEN) as PRAD_LOCK_TOKEN,
  trim(tbl.PRAD_LONG) as PRAD_LONG,
  trim(tbl.PRAD_MCTR_TRSN) as PRAD_MCTR_TRSN,
  trim(tbl.PRAD_MEL_RTRN_CD_NVL) as PRAD_MEL_RTRN_CD_NVL,
  trim(tbl.PRAD_PHONE) as PRAD_PHONE,
  trim(tbl.PRAD_PHONE_EXT) as PRAD_PHONE_EXT,
  trim(tbl.PRAD_PRACTICE_IND) as PRAD_PRACTICE_IND,
  trim(tbl.PRAD_STATE) as PRAD_STATE,
  trim(tbl.PRAD_TERM_DT) as PRAD_TERM_DT,
  trim(tbl.PRAD_TYPE) as PRAD_TYPE,
  trim(tbl.PRAD_TYPE_MAIL) as PRAD_TYPE_MAIL,
  trim(tbl.PRAD_ZIP) as PRAD_ZIP,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_prad_address tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(PRAD_ADDR1),
  trim(PRAD_ADDR2),
  trim(PRAD_ADDR3),
  trim(PRAD_CITY),
  trim(PRAD_CITY_XLOW),
  trim(PRAD_COUNTY),
  trim(PRAD_CTRY_CD),
  trim(PRAD_DIRECTORY_IND),
  trim(PRAD_EFF_DT),
  trim(PRAD_EMAIL),
  trim(PRAD_FAX),
  trim(PRAD_FAX_EXT),
  trim(PRAD_GEO_RTRN_CD),
  trim(PRAD_HD_IND),
  trim(PRAD_ID),
  trim(PRAD_LAT),
  trim(PRAD_LOCK_TOKEN),
  trim(PRAD_LONG),
  trim(PRAD_MCTR_TRSN),
  trim(PRAD_MEL_RTRN_CD_NVL),
  trim(PRAD_PHONE),
  trim(PRAD_PHONE_EXT),
  trim(PRAD_PRACTICE_IND),
  trim(PRAD_STATE),
  trim(PRAD_TERM_DT),
  trim(PRAD_TYPE),
  trim(PRAD_TYPE_MAIL),
  trim(PRAD_ZIP),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_clhi_proc_desc AS
SELECT
  
FROM bronze.tbl_clhi_proc_desc tbl
GROUP BY
  ;
CREATE OR REPLACE VIEW silver.V_tbl_clst_status AS
SELECT
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLMI_ITS_CUR_STS) as CLMI_ITS_CUR_STS,
  trim(tbl.CLST_LOCK_TOKEN) as CLST_LOCK_TOKEN,
  trim(tbl.CLST_MCTR_REAS) as CLST_MCTR_REAS,
  trim(tbl.CLST_SEQ_NO) as CLST_SEQ_NO,
  trim(tbl.CLST_STS) as CLST_STS,
  trim(tbl.CLST_STS_DTM) as CLST_STS_DTM,
  trim(tbl.CLST_USID_ROUTE) as CLST_USID_ROUTE,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.USUS_ID) as USUS_ID
FROM bronze.tbl_clst_status tbl
GROUP BY
  trim(CLCL_ID),
  trim(CLMI_ITS_CUR_STS),
  trim(CLST_LOCK_TOKEN),
  trim(CLST_MCTR_REAS),
  trim(CLST_SEQ_NO),
  trim(CLST_STS),
  trim(CLST_STS_DTM),
  trim(CLST_USID_ROUTE),
  trim(MEME_CK),
  trim(USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_clip_its_patnt AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLIP_ADDL_DATA) as CLIP_ADDL_DATA,
  trim(tbl.CLIP_ADDR1) as CLIP_ADDR1,
  trim(tbl.CLIP_ADDR2) as CLIP_ADDR2,
  trim(tbl.CLIP_BIRTH_DT) as CLIP_BIRTH_DT,
  trim(tbl.CLIP_CITY) as CLIP_CITY,
  trim(tbl.CLIP_EMPLOY_STS_CD) as CLIP_EMPLOY_STS_CD,
  trim(tbl.CLIP_FIRST_NAME) as CLIP_FIRST_NAME,
  trim(tbl.CLIP_LAST_NAME) as CLIP_LAST_NAME,
  trim(tbl.CLIP_LOCK_TOKEN) as CLIP_LOCK_TOKEN,
  trim(tbl.CLIP_MARITAL_IND) as CLIP_MARITAL_IND,
  trim(tbl.CLIP_MID_INIT) as CLIP_MID_INIT,
  trim(tbl.CLIP_REL) as CLIP_REL,
  trim(tbl.CLIP_SB_EMP_ADDR) as CLIP_SB_EMP_ADDR,
  trim(tbl.CLIP_SB_EMP_CITY) as CLIP_SB_EMP_CITY,
  trim(tbl.CLIP_SB_EMP_SCHL) as CLIP_SB_EMP_SCHL,
  trim(tbl.CLIP_SB_EMP_STATE) as CLIP_SB_EMP_STATE,
  trim(tbl.CLIP_SB_EMP_ZIP) as CLIP_SB_EMP_ZIP,
  trim(tbl.CLIP_SB_GROUP_NO) as CLIP_SB_GROUP_NO,
  trim(tbl.CLIP_SEX) as CLIP_SEX,
  trim(tbl.CLIP_STATE) as CLIP_STATE,
  trim(tbl.CLIP_STUDENT_STS) as CLIP_STUDENT_STS,
  trim(tbl.CLIP_ZIP) as CLIP_ZIP,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clip_its_patnt tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CLCL_ID),
  trim(CLIP_ADDL_DATA),
  trim(CLIP_ADDR1),
  trim(CLIP_ADDR2),
  trim(CLIP_BIRTH_DT),
  trim(CLIP_CITY),
  trim(CLIP_EMPLOY_STS_CD),
  trim(CLIP_FIRST_NAME),
  trim(CLIP_LAST_NAME),
  trim(CLIP_LOCK_TOKEN),
  trim(CLIP_MARITAL_IND),
  trim(CLIP_MID_INIT),
  trim(CLIP_REL),
  trim(CLIP_SB_EMP_ADDR),
  trim(CLIP_SB_EMP_CITY),
  trim(CLIP_SB_EMP_SCHL),
  trim(CLIP_SB_EMP_STATE),
  trim(CLIP_SB_EMP_ZIP),
  trim(CLIP_SB_GROUP_NO),
  trim(CLIP_SEX),
  trim(CLIP_STATE),
  trim(CLIP_STUDENT_STS),
  trim(CLIP_ZIP),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_clpp_its_prov AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLPP_ADDL_DATA) as CLPP_ADDL_DATA,
  trim(tbl.CLPP_ATTD_PR_ID) as CLPP_ATTD_PR_ID,
  trim(tbl.CLPP_ATTD_PR_NAME) as CLPP_ATTD_PR_NAME,
  trim(tbl.CLPP_ATTD_PR_QUAL) as CLPP_ATTD_PR_QUAL,
  trim(tbl.CLPP_BCBS_PR_ID) as CLPP_BCBS_PR_ID,
  trim(tbl.CLPP_BCBS_PR_NPI) as CLPP_BCBS_PR_NPI,
  trim(tbl.CLPP_CLASS_PROV) as CLPP_CLASS_PROV,
  trim(tbl.CLPP_CLM_SUB_ORG) as CLPP_CLM_SUB_ORG,
  trim(tbl.CLPP_CNTRY_CD) as CLPP_CNTRY_CD,
  trim(tbl.CLPP_FAC_TYPE) as CLPP_FAC_TYPE,
  trim(tbl.CLPP_FED_TAX_ID) as CLPP_FED_TAX_ID,
  trim(tbl.CLPP_FLEX_NTWK_GRP_NVL) as CLPP_FLEX_NTWK_GRP_NVL,
  trim(tbl.CLPP_LOCK_TOKEN) as CLPP_LOCK_TOKEN,
  trim(tbl.CLPP_MARKET_ID_NVL) as CLPP_MARKET_ID_NVL,
  trim(tbl.CLPP_MED_PROV_NUM) as CLPP_MED_PROV_NUM,
  trim(tbl.CLPP_OP_PR_ID) as CLPP_OP_PR_ID,
  trim(tbl.CLPP_OP_PR_ID_QUAL) as CLPP_OP_PR_ID_QUAL,
  trim(tbl.CLPP_OP_PR_NAME) as CLPP_OP_PR_NAME,
  trim(tbl.CLPP_OTH_PAY_ADDR) as CLPP_OTH_PAY_ADDR,
  trim(tbl.CLPP_OTH_PAY_CITY) as CLPP_OTH_PAY_CITY,
  trim(tbl.CLPP_OTH_PAY_NAME) as CLPP_OTH_PAY_NAME,
  trim(tbl.CLPP_OTH_PAY_NUM) as CLPP_OTH_PAY_NUM,
  trim(tbl.CLPP_OTH_PAY_ST) as CLPP_OTH_PAY_ST,
  trim(tbl.CLPP_OTH_PAY_ZIP) as CLPP_OTH_PAY_ZIP,
  trim(tbl.CLPP_OTH_PAYEE_NPI) as CLPP_OTH_PAYEE_NPI,
  trim(tbl.CLPP_OTH1_PR_ID) as CLPP_OTH1_PR_ID,
  trim(tbl.CLPP_OTH1_PR_NAME) as CLPP_OTH1_PR_NAME,
  trim(tbl.CLPP_OTH1_PR_QUAL) as CLPP_OTH1_PR_QUAL,
  trim(tbl.CLPP_OTH2_PR_ID) as CLPP_OTH2_PR_ID,
  trim(tbl.CLPP_OTH2_PR_NAME) as CLPP_OTH2_PR_NAME,
  trim(tbl.CLPP_PERF_ID) as CLPP_PERF_ID,
  trim(tbl.CLPP_PERF_ID_NPI) as CLPP_PERF_ID_NPI,
  trim(tbl.CLPP_PERF_IHS_IND_NVL) as CLPP_PERF_IHS_IND_NVL,
  trim(tbl.CLPP_PERF_NAME) as CLPP_PERF_NAME,
  trim(tbl.CLPP_PERF_SPEC) as CLPP_PERF_SPEC,
  trim(tbl.CLPP_PERF_TYPE) as CLPP_PERF_TYPE,
  trim(tbl.CLPP_PERF_ZIP) as CLPP_PERF_ZIP,
  trim(tbl.CLPP_PHONE) as CLPP_PHONE,
  trim(tbl.CLPP_PPO_AVAIL_IND) as CLPP_PPO_AVAIL_IND,
  trim(tbl.CLPP_PR_ADDR1) as CLPP_PR_ADDR1,
  trim(tbl.CLPP_PR_ADDR2) as CLPP_PR_ADDR2,
  trim(tbl.CLPP_PR_CITY) as CLPP_PR_CITY,
  trim(tbl.CLPP_PR_NAME) as CLPP_PR_NAME,
  trim(tbl.CLPP_PR_STATE) as CLPP_PR_STATE,
  trim(tbl.CLPP_PRPR_TYP_AVLB) as CLPP_PRPR_TYP_AVLB,
  trim(tbl.CLPP_REF_PR_ID) as CLPP_REF_PR_ID,
  trim(tbl.CLPP_REF_PR_NAME) as CLPP_REF_PR_NAME,
  trim(tbl.CLPP_REF_PRID_QUAL) as CLPP_REF_PRID_QUAL,
  trim(tbl.CLPP_SVC_FAC_ID) as CLPP_SVC_FAC_ID,
  trim(tbl.CLPP_SVC_FAC_NAME) as CLPP_SVC_FAC_NAME,
  trim(tbl.CLPP_SVC_FAC_QUAL) as CLPP_SVC_FAC_QUAL,
  trim(tbl.CLPP_SVC_FAC_ST) as CLPP_SVC_FAC_ST,
  trim(tbl.CLPP_SVC_FAC_ZIP) as CLPP_SVC_FAC_ZIP,
  trim(tbl.CLPP_TAXONOMY_CD) as CLPP_TAXONOMY_CD,
  trim(tbl.CLPP_TIER_DSGN_IND_NVL) as CLPP_TIER_DSGN_IND_NVL,
  trim(tbl.CLPP_ZIP) as CLPP_ZIP,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clpp_its_prov tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CLCL_ID),
  trim(CLPP_ADDL_DATA),
  trim(CLPP_ATTD_PR_ID),
  trim(CLPP_ATTD_PR_NAME),
  trim(CLPP_ATTD_PR_QUAL),
  trim(CLPP_BCBS_PR_ID),
  trim(CLPP_BCBS_PR_NPI),
  trim(CLPP_CLASS_PROV),
  trim(CLPP_CLM_SUB_ORG),
  trim(CLPP_CNTRY_CD),
  trim(CLPP_FAC_TYPE),
  trim(CLPP_FED_TAX_ID),
  trim(CLPP_FLEX_NTWK_GRP_NVL),
  trim(CLPP_LOCK_TOKEN),
  trim(CLPP_MARKET_ID_NVL),
  trim(CLPP_MED_PROV_NUM),
  trim(CLPP_OP_PR_ID),
  trim(CLPP_OP_PR_ID_QUAL),
  trim(CLPP_OP_PR_NAME),
  trim(CLPP_OTH_PAY_ADDR),
  trim(CLPP_OTH_PAY_CITY),
  trim(CLPP_OTH_PAY_NAME),
  trim(CLPP_OTH_PAY_NUM),
  trim(CLPP_OTH_PAY_ST),
  trim(CLPP_OTH_PAY_ZIP),
  trim(CLPP_OTH_PAYEE_NPI),
  trim(CLPP_OTH1_PR_ID),
  trim(CLPP_OTH1_PR_NAME),
  trim(CLPP_OTH1_PR_QUAL),
  trim(CLPP_OTH2_PR_ID),
  trim(CLPP_OTH2_PR_NAME),
  trim(CLPP_PERF_ID),
  trim(CLPP_PERF_ID_NPI),
  trim(CLPP_PERF_IHS_IND_NVL),
  trim(CLPP_PERF_NAME),
  trim(CLPP_PERF_SPEC),
  trim(CLPP_PERF_TYPE),
  trim(CLPP_PERF_ZIP),
  trim(CLPP_PHONE),
  trim(CLPP_PPO_AVAIL_IND),
  trim(CLPP_PR_ADDR1),
  trim(CLPP_PR_ADDR2),
  trim(CLPP_PR_CITY),
  trim(CLPP_PR_NAME),
  trim(CLPP_PR_STATE),
  trim(CLPP_PRPR_TYP_AVLB),
  trim(CLPP_REF_PR_ID),
  trim(CLPP_REF_PR_NAME),
  trim(CLPP_REF_PRID_QUAL),
  trim(CLPP_SVC_FAC_ID),
  trim(CLPP_SVC_FAC_NAME),
  trim(CLPP_SVC_FAC_QUAL),
  trim(CLPP_SVC_FAC_ST),
  trim(CLPP_SVC_FAC_ZIP),
  trim(CLPP_TAXONOMY_CD),
  trim(CLPP_TIER_DSGN_IND_NVL),
  trim(CLPP_ZIP),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_clhi_pivot AS
SELECT
  
FROM bronze.tbl_clhi_pivot tbl
GROUP BY
  ;
CREATE OR REPLACE VIEW silver.V_tbl_cdpp_li_its_pr AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CDML_SEQ_NO) as CDML_SEQ_NO,
  trim(tbl.CDPP_ADDL_DATA) as CDPP_ADDL_DATA,
  trim(tbl.CDPP_CLASS_PROV) as CDPP_CLASS_PROV,
  trim(tbl.CDPP_FLEX_NTWK_GRP_NVL) as CDPP_FLEX_NTWK_GRP_NVL,
  trim(tbl.CDPP_LOCK_TOKEN) as CDPP_LOCK_TOKEN,
  trim(tbl.CDPP_MARKET_ID_NVL) as CDPP_MARKET_ID_NVL,
  trim(tbl.CDPP_PERF_ID) as CDPP_PERF_ID,
  trim(tbl.CDPP_PERF_ID_NPI) as CDPP_PERF_ID_NPI,
  trim(tbl.CDPP_PERF_IHS_IND_NVL) as CDPP_PERF_IHS_IND_NVL,
  trim(tbl.CDPP_PERF_NAME) as CDPP_PERF_NAME,
  trim(tbl.CDPP_PERF_SPEC) as CDPP_PERF_SPEC,
  trim(tbl.CDPP_PERF_TYPE) as CDPP_PERF_TYPE,
  trim(tbl.CDPP_PERF_ZIP) as CDPP_PERF_ZIP,
  trim(tbl.CDPP_PRPR_TYP_AVLB) as CDPP_PRPR_TYP_AVLB,
  trim(tbl.CDPP_SVC_FAC_ID) as CDPP_SVC_FAC_ID,
  trim(tbl.CDPP_SVC_FAC_QUAL) as CDPP_SVC_FAC_QUAL,
  trim(tbl.CDPP_SVC_FAC_ST) as CDPP_SVC_FAC_ST,
  trim(tbl.CDPP_SVC_FAC_ZIP) as CDPP_SVC_FAC_ZIP,
  trim(tbl.CDPP_TAXONOMY_CD) as CDPP_TAXONOMY_CD,
  trim(tbl.CDPP_TIER_DSGN_IND_NVL) as CDPP_TIER_DSGN_IND_NVL,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_cdpp_li_its_pr tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CDML_SEQ_NO),
  trim(CDPP_ADDL_DATA),
  trim(CDPP_CLASS_PROV),
  trim(CDPP_FLEX_NTWK_GRP_NVL),
  trim(CDPP_LOCK_TOKEN),
  trim(CDPP_MARKET_ID_NVL),
  trim(CDPP_PERF_ID),
  trim(CDPP_PERF_ID_NPI),
  trim(CDPP_PERF_IHS_IND_NVL),
  trim(CDPP_PERF_NAME),
  trim(CDPP_PERF_SPEC),
  trim(CDPP_PERF_TYPE),
  trim(CDPP_PERF_ZIP),
  trim(CDPP_PRPR_TYP_AVLB),
  trim(CDPP_SVC_FAC_ID),
  trim(CDPP_SVC_FAC_QUAL),
  trim(CDPP_SVC_FAC_ST),
  trim(CDPP_SVC_FAC_ZIP),
  trim(CDPP_TAXONOMY_CD),
  trim(CDPP_TIER_DSGN_IND_NVL),
  trim(CLCL_ID),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_clmi_misc AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLMI_835_IND) as CLMI_835_IND,
  trim(tbl.CLMI_ADDL_DATA) as CLMI_ADDL_DATA,
  trim(tbl.CLMI_ADJ_RECD_DT) as CLMI_ADJ_RECD_DT,
  trim(tbl.CLMI_ADJ_RSN_CD) as CLMI_ADJ_RSN_CD,
  trim(tbl.CLMI_ADJ_SF_IND) as CLMI_ADJ_SF_IND,
  trim(tbl.CLMI_ASO_IND) as CLMI_ASO_IND,
  trim(tbl.CLMI_ASSIGN_BN_IND) as CLMI_ASSIGN_BN_IND,
  trim(tbl.CLMI_ATTACH_IND) as CLMI_ATTACH_IND,
  trim(tbl.CLMI_BCP_PROD_TYPE_NVL) as CLMI_BCP_PROD_TYPE_NVL,
  trim(tbl.CLMI_BOID) as CLMI_BOID,
  trim(tbl.CLMI_CARVE_BEG_DT) as CLMI_CARVE_BEG_DT,
  trim(tbl.CLMI_CARVE_END_DT) as CLMI_CARVE_END_DT,
  trim(tbl.CLMI_CARVEOUT_DAYS) as CLMI_CARVEOUT_DAYS,
  trim(tbl.CLMI_CARVEOUT_IND) as CLMI_CARVEOUT_IND,
  trim(tbl.CLMI_CASE_ALLW_AMT) as CLMI_CASE_ALLW_AMT,
  trim(tbl.CLMI_CFA_DISP_DT) as CLMI_CFA_DISP_DT,
  trim(tbl.CLMI_DELIVERY_METH) as CLMI_DELIVERY_METH,
  trim(tbl.CLMI_DF_CHK_DT) as CLMI_DF_CHK_DT,
  trim(tbl.CLMI_DF_CHK_NUM) as CLMI_DF_CHK_NUM,
  trim(tbl.CLMI_ECR_CD) as CLMI_ECR_CD,
  trim(tbl.CLMI_ESTIMATE_IND) as CLMI_ESTIMATE_IND,
  trim(tbl.CLMI_EXCESS_DAYS_NVL) as CLMI_EXCESS_DAYS_NVL,
  trim(tbl.CLMI_FEE_SOURCE_CD_NVL) as CLMI_FEE_SOURCE_CD_NVL,
  trim(tbl.CLMI_HOME_PLAN_CD) as CLMI_HOME_PLAN_CD,
  trim(tbl.CLMI_HOST_PLAN_CD) as CLMI_HOST_PLAN_CD,
  trim(tbl.CLMI_ICALC_DIS_AMT) as CLMI_ICALC_DIS_AMT,
  trim(tbl.CLMI_INP_METH_ACT_NVL) as CLMI_INP_METH_ACT_NVL,
  trim(tbl.CLMI_INTL_CD) as CLMI_INTL_CD,
  trim(tbl.CLMI_INVEST_BEG_DT) as CLMI_INVEST_BEG_DT,
  trim(tbl.CLMI_INVEST_DAYS) as CLMI_INVEST_DAYS,
  trim(tbl.CLMI_INVEST_END_DT) as CLMI_INVEST_END_DT,
  trim(tbl.CLMI_INVEST_IND) as CLMI_INVEST_IND,
  trim(tbl.CLMI_INVEST_REC_DT_NVL) as CLMI_INVEST_REC_DT_NVL,
  trim(tbl.CLMI_ITS_ADM_AMT) as CLMI_ITS_ADM_AMT,
  trim(tbl.CLMI_ITS_AMT) as CLMI_ITS_AMT,
  trim(tbl.CLMI_ITS_CL_TYPE) as CLMI_ITS_CL_TYPE,
  trim(tbl.CLMI_ITS_CLM_ID) as CLMI_ITS_CLM_ID,
  trim(tbl.CLMI_ITS_CUR_STS) as CLMI_ITS_CUR_STS,
  trim(tbl.CLMI_ITS_FEE) as CLMI_ITS_FEE,
  trim(tbl.CLMI_ITS_FUNC_CD) as CLMI_ITS_FUNC_CD,
  trim(tbl.CLMI_ITS_NPOS_IND) as CLMI_ITS_NPOS_IND,
  trim(tbl.CLMI_ITS_SB_ID_ACT) as CLMI_ITS_SB_ID_ACT,
  trim(tbl.CLMI_ITS_SBSB_ID) as CLMI_ITS_SBSB_ID,
  trim(tbl.CLMI_ITS_SCCF_NO) as CLMI_ITS_SCCF_NO,
  trim(tbl.CLMI_ITS_SUB_TYPE) as CLMI_ITS_SUB_TYPE,
  trim(tbl.CLMI_ITSPFX_ACCTID_NVL) as CLMI_ITSPFX_ACCTID_NVL,
  trim(tbl.CLMI_LINE_BUS_CD) as CLMI_LINE_BUS_CD,
  trim(tbl.CLMI_LOCAL_PLAN_CD) as CLMI_LOCAL_PLAN_CD,
  trim(tbl.CLMI_LOCK_TOKEN) as CLMI_LOCK_TOKEN,
  trim(tbl.CLMI_MPPQ_ASGN) as CLMI_MPPQ_ASGN,
  trim(tbl.CLMI_MPPQ_UNASGN) as CLMI_MPPQ_UNASGN,
  trim(tbl.CLMI_NAT_OOA_CD) as CLMI_NAT_OOA_CD,
  trim(tbl.CLMI_OPL_PR_ARG_CD) as CLMI_OPL_PR_ARG_CD,
  trim(tbl.CLMI_OUTLAB_AMT) as CLMI_OUTLAB_AMT,
  trim(tbl.CLMI_PAT_SIGN_SRCE) as CLMI_PAT_SIGN_SRCE,
  trim(tbl.CLMI_PCT_FCTR) as CLMI_PCT_FCTR,
  trim(tbl.CLMI_PER_DIEM_RATE) as CLMI_PER_DIEM_RATE,
  trim(tbl.CLMI_PERF_POS_IND) as CLMI_PERF_POS_IND,
  trim(tbl.CLMI_PFX_ACCTID_IND_NVL) as CLMI_PFX_ACCTID_IND_NVL,
  trim(tbl.CLMI_PLAN_PAYER_CD) as CLMI_PLAN_PAYER_CD,
  trim(tbl.CLMI_PMT_RSTRC_IND) as CLMI_PMT_RSTRC_IND,
  trim(tbl.CLMI_POS_PRC_IND) as CLMI_POS_PRC_IND,
  trim(tbl.CLMI_PRCE_METH) as CLMI_PRCE_METH,
  trim(tbl.CLMI_PRCE_PRI_RULE) as CLMI_PRCE_PRI_RULE,
  trim(tbl.CLMI_PRCE_SEC_RULE) as CLMI_PRCE_SEC_RULE,
  trim(tbl.CLMI_PRCS_SITE_CD) as CLMI_PRCS_SITE_CD,
  trim(tbl.CLMI_PROF_BILL_TYP) as CLMI_PROF_BILL_TYP,
  trim(tbl.CLMI_PROGRAM_CODE) as CLMI_PROGRAM_CODE,
  trim(tbl.CLMI_PVT_ROOM_RATE) as CLMI_PVT_ROOM_RATE,
  trim(tbl.CLMI_RF_DATE_PAID_NVL) as CLMI_RF_DATE_PAID_NVL,
  trim(tbl.CLMI_SF_REL_NUM_NVL) as CLMI_SF_REL_NUM_NVL,
  trim(tbl.CLMI_SP_ROOM_RATE) as CLMI_SP_ROOM_RATE,
  trim(tbl.CLMI_SPPQ_IND) as CLMI_SPPQ_IND,
  trim(tbl.CLMI_STRLN_ADJ_IND) as CLMI_STRLN_ADJ_IND,
  trim(tbl.CLMI_SUD_IND_NVL) as CLMI_SUD_IND_NVL,
  trim(tbl.CLMI_SUPP_DISC_AMT) as CLMI_SUPP_DISC_AMT,
  trim(tbl.CLMI_SURCHG_AMT) as CLMI_SURCHG_AMT,
  trim(tbl.CLMI_WORK_COMP_IND) as CLMI_WORK_COMP_IND,
  trim(tbl.CLMI_XREF_SCCF_NO) as CLMI_XREF_SCCF_NO,
  trim(tbl.ITPC_ID) as ITPC_ID,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clmi_misc tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CLCL_ID),
  trim(CLMI_835_IND),
  trim(CLMI_ADDL_DATA),
  trim(CLMI_ADJ_RECD_DT),
  trim(CLMI_ADJ_RSN_CD),
  trim(CLMI_ADJ_SF_IND),
  trim(CLMI_ASO_IND),
  trim(CLMI_ASSIGN_BN_IND),
  trim(CLMI_ATTACH_IND),
  trim(CLMI_BCP_PROD_TYPE_NVL),
  trim(CLMI_BOID),
  trim(CLMI_CARVE_BEG_DT),
  trim(CLMI_CARVE_END_DT),
  trim(CLMI_CARVEOUT_DAYS),
  trim(CLMI_CARVEOUT_IND),
  trim(CLMI_CASE_ALLW_AMT),
  trim(CLMI_CFA_DISP_DT),
  trim(CLMI_DELIVERY_METH),
  trim(CLMI_DF_CHK_DT),
  trim(CLMI_DF_CHK_NUM),
  trim(CLMI_ECR_CD),
  trim(CLMI_ESTIMATE_IND),
  trim(CLMI_EXCESS_DAYS_NVL),
  trim(CLMI_FEE_SOURCE_CD_NVL),
  trim(CLMI_HOME_PLAN_CD),
  trim(CLMI_HOST_PLAN_CD),
  trim(CLMI_ICALC_DIS_AMT),
  trim(CLMI_INP_METH_ACT_NVL),
  trim(CLMI_INTL_CD),
  trim(CLMI_INVEST_BEG_DT),
  trim(CLMI_INVEST_DAYS),
  trim(CLMI_INVEST_END_DT),
  trim(CLMI_INVEST_IND),
  trim(CLMI_INVEST_REC_DT_NVL),
  trim(CLMI_ITS_ADM_AMT),
  trim(CLMI_ITS_AMT),
  trim(CLMI_ITS_CL_TYPE),
  trim(CLMI_ITS_CLM_ID),
  trim(CLMI_ITS_CUR_STS),
  trim(CLMI_ITS_FEE),
  trim(CLMI_ITS_FUNC_CD),
  trim(CLMI_ITS_NPOS_IND),
  trim(CLMI_ITS_SB_ID_ACT),
  trim(CLMI_ITS_SBSB_ID),
  trim(CLMI_ITS_SCCF_NO),
  trim(CLMI_ITS_SUB_TYPE),
  trim(CLMI_ITSPFX_ACCTID_NVL),
  trim(CLMI_LINE_BUS_CD),
  trim(CLMI_LOCAL_PLAN_CD),
  trim(CLMI_LOCK_TOKEN),
  trim(CLMI_MPPQ_ASGN),
  trim(CLMI_MPPQ_UNASGN),
  trim(CLMI_NAT_OOA_CD),
  trim(CLMI_OPL_PR_ARG_CD),
  trim(CLMI_OUTLAB_AMT),
  trim(CLMI_PAT_SIGN_SRCE),
  trim(CLMI_PCT_FCTR),
  trim(CLMI_PER_DIEM_RATE),
  trim(CLMI_PERF_POS_IND),
  trim(CLMI_PFX_ACCTID_IND_NVL),
  trim(CLMI_PLAN_PAYER_CD),
  trim(CLMI_PMT_RSTRC_IND),
  trim(CLMI_POS_PRC_IND),
  trim(CLMI_PRCE_METH),
  trim(CLMI_PRCE_PRI_RULE),
  trim(CLMI_PRCE_SEC_RULE),
  trim(CLMI_PRCS_SITE_CD),
  trim(CLMI_PROF_BILL_TYP),
  trim(CLMI_PROGRAM_CODE),
  trim(CLMI_PVT_ROOM_RATE),
  trim(CLMI_RF_DATE_PAID_NVL),
  trim(CLMI_SF_REL_NUM_NVL),
  trim(CLMI_SP_ROOM_RATE),
  trim(CLMI_SPPQ_IND),
  trim(CLMI_STRLN_ADJ_IND),
  trim(CLMI_SUD_IND_NVL),
  trim(CLMI_SUPP_DISC_AMT),
  trim(CLMI_SURCHG_AMT),
  trim(CLMI_WORK_COMP_IND),
  trim(CLMI_XREF_SCCF_NO),
  trim(ITPC_ID),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_clor_cl_ovr AS
SELECT
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLOR_AUTO_GEN) as CLOR_AUTO_GEN,
  trim(tbl.CLOR_LOCK_TOKEN) as CLOR_LOCK_TOKEN,
  trim(tbl.CLOR_OR_AMOUNT) as CLOR_OR_AMOUNT,
  trim(tbl.CLOR_OR_DT) as CLOR_OR_DT,
  trim(tbl.CLOR_OR_ID) as CLOR_OR_ID,
  trim(tbl.CLOR_OR_USID) as CLOR_OR_USID,
  trim(tbl.CLOR_OR_VALUE) as CLOR_OR_VALUE,
  trim(tbl.EXCD_ID) as EXCD_ID,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clor_cl_ovr tbl
GROUP BY
  trim(CLCL_ID),
  trim(CLOR_AUTO_GEN),
  trim(CLOR_LOCK_TOKEN),
  trim(CLOR_OR_AMOUNT),
  trim(CLOR_OR_DT),
  trim(CLOR_OR_ID),
  trim(CLOR_OR_USID),
  trim(CLOR_OR_VALUE),
  trim(EXCD_ID),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_sgsg_sub_group AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CSCS_ID) as CSCS_ID,
  trim(tbl.EXCD_ID) as EXCD_ID,
  trim(tbl.GRGR_CK) as GRGR_CK,
  trim(tbl.SGSG_ADDR1) as SGSG_ADDR1,
  trim(tbl.SGSG_ADDR2) as SGSG_ADDR2,
  trim(tbl.SGSG_ADDR3) as SGSG_ADDR3,
  trim(tbl.SGSG_BL_CONV_DT) as SGSG_BL_CONV_DT,
  trim(tbl.SGSG_CITY) as SGSG_CITY,
  trim(tbl.SGSG_CITY_XLOW) as SGSG_CITY_XLOW,
  trim(tbl.SGSG_CK) as SGSG_CK,
  trim(tbl.SGSG_CONT_EFF_DT) as SGSG_CONT_EFF_DT,
  trim(tbl.SGSG_CONV_DT) as SGSG_CONV_DT,
  trim(tbl.SGSG_COUNTY) as SGSG_COUNTY,
  trim(tbl.SGSG_CTRY_CD) as SGSG_CTRY_CD,
  trim(tbl.SGSG_CURR_ANNV_DT) as SGSG_CURR_ANNV_DT,
  trim(tbl.SGSG_EIN) as SGSG_EIN,
  trim(tbl.SGSG_EMAIL) as SGSG_EMAIL,
  trim(tbl.SGSG_ERIS_MMDD) as SGSG_ERIS_MMDD,
  trim(tbl.SGSG_EXTN_ADDR_IND) as SGSG_EXTN_ADDR_IND,
  trim(tbl.SGSG_FAX) as SGSG_FAX,
  trim(tbl.SGSG_FAX_EXT) as SGSG_FAX_EXT,
  trim(tbl.SGSG_ID) as SGSG_ID,
  trim(tbl.SGSG_LOCK_TOKEN) as SGSG_LOCK_TOKEN,
  trim(tbl.SGSG_MCTR_LANG) as SGSG_MCTR_LANG,
  trim(tbl.SGSG_MCTR_PTYP) as SGSG_MCTR_PTYP,
  trim(tbl.SGSG_MCTR_TRSN) as SGSG_MCTR_TRSN,
  trim(tbl.SGSG_MCTR_TYPE) as SGSG_MCTR_TYPE,
  trim(tbl.SGSG_MCTR_VIP) as SGSG_MCTR_VIP,
  trim(tbl.SGSG_NAME) as SGSG_NAME,
  trim(tbl.SGSG_NAME_XLOW) as SGSG_NAME_XLOW,
  trim(tbl.SGSG_NEXT_ANNV_DT) as SGSG_NEXT_ANNV_DT,
  trim(tbl.SGSG_ORIG_EFF_DT) as SGSG_ORIG_EFF_DT,
  trim(tbl.SGSG_PHONE) as SGSG_PHONE,
  trim(tbl.SGSG_PHONE_EXT) as SGSG_PHONE_EXT,
  trim(tbl.SGSG_POL_NO) as SGSG_POL_NO,
  trim(tbl.SGSG_PREV_ANNV_DT) as SGSG_PREV_ANNV_DT,
  trim(tbl.SGSG_PUP_IND_NVL) as SGSG_PUP_IND_NVL,
  trim(tbl.SGSG_RECD_DT) as SGSG_RECD_DT,
  trim(tbl.SGSG_RENEW_MMDD) as SGSG_RENEW_MMDD,
  trim(tbl.SGSG_RNST_DT) as SGSG_RNST_DT,
  trim(tbl.SGSG_RNST_TYPE) as SGSG_RNST_TYPE,
  trim(tbl.SGSG_RNST_VAL) as SGSG_RNST_VAL,
  trim(tbl.SGSG_RUNOUT_DT) as SGSG_RUNOUT_DT,
  trim(tbl.SGSG_RUNOUT_EXCD) as SGSG_RUNOUT_EXCD,
  trim(tbl.SGSG_STATE) as SGSG_STATE,
  trim(tbl.SGSG_STS) as SGSG_STS,
  trim(tbl.SGSG_TERM_DT) as SGSG_TERM_DT,
  trim(tbl.SGSG_TERM_PREM_MOS) as SGSG_TERM_PREM_MOS,
  trim(tbl.SGSG_TOTAL_CONTR) as SGSG_TOTAL_CONTR,
  trim(tbl.SGSG_TOTAL_ELIG) as SGSG_TOTAL_ELIG,
  trim(tbl.SGSG_TOTAL_EMPL) as SGSG_TOTAL_EMPL,
  trim(tbl.SGSG_TRANS_ACCEPT) as SGSG_TRANS_ACCEPT,
  trim(tbl.SGSG_UNDW_USUS_ID) as SGSG_UNDW_USUS_ID,
  trim(tbl.SGSG_ZIP) as SGSG_ZIP,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID,
  trim(tbl.WMDS_SEQ_NO) as WMDS_SEQ_NO
FROM bronze.tbl_sgsg_sub_group tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CSCS_ID),
  trim(EXCD_ID),
  trim(GRGR_CK),
  trim(SGSG_ADDR1),
  trim(SGSG_ADDR2),
  trim(SGSG_ADDR3),
  trim(SGSG_BL_CONV_DT),
  trim(SGSG_CITY),
  trim(SGSG_CITY_XLOW),
  trim(SGSG_CK),
  trim(SGSG_CONT_EFF_DT),
  trim(SGSG_CONV_DT),
  trim(SGSG_COUNTY),
  trim(SGSG_CTRY_CD),
  trim(SGSG_CURR_ANNV_DT),
  trim(SGSG_EIN),
  trim(SGSG_EMAIL),
  trim(SGSG_ERIS_MMDD),
  trim(SGSG_EXTN_ADDR_IND),
  trim(SGSG_FAX),
  trim(SGSG_FAX_EXT),
  trim(SGSG_ID),
  trim(SGSG_LOCK_TOKEN),
  trim(SGSG_MCTR_LANG),
  trim(SGSG_MCTR_PTYP),
  trim(SGSG_MCTR_TRSN),
  trim(SGSG_MCTR_TYPE),
  trim(SGSG_MCTR_VIP),
  trim(SGSG_NAME),
  trim(SGSG_NAME_XLOW),
  trim(SGSG_NEXT_ANNV_DT),
  trim(SGSG_ORIG_EFF_DT),
  trim(SGSG_PHONE),
  trim(SGSG_PHONE_EXT),
  trim(SGSG_POL_NO),
  trim(SGSG_PREV_ANNV_DT),
  trim(SGSG_PUP_IND_NVL),
  trim(SGSG_RECD_DT),
  trim(SGSG_RENEW_MMDD),
  trim(SGSG_RNST_DT),
  trim(SGSG_RNST_TYPE),
  trim(SGSG_RNST_VAL),
  trim(SGSG_RUNOUT_DT),
  trim(SGSG_RUNOUT_EXCD),
  trim(SGSG_STATE),
  trim(SGSG_STS),
  trim(SGSG_TERM_DT),
  trim(SGSG_TERM_PREM_MOS),
  trim(SGSG_TOTAL_CONTR),
  trim(SGSG_TOTAL_ELIG),
  trim(SGSG_TOTAL_EMPL),
  trim(SGSG_TRANS_ACCEPT),
  trim(SGSG_UNDW_USUS_ID),
  trim(SGSG_ZIP),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID),
  trim(WMDS_SEQ_NO);
CREATE OR REPLACE VIEW silver.V_tbl_clmd_diag AS
SELECT
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLMD_IDCD_MAN_IND) as CLMD_IDCD_MAN_IND,
  trim(tbl.CLMD_LOCK_TOKEN) as CLMD_LOCK_TOKEN,
  trim(tbl.CLMD_POA_IND) as CLMD_POA_IND,
  trim(tbl.CLMD_TYPE) as CLMD_TYPE,
  trim(tbl.IDCD_ID) as IDCD_ID,
  trim(tbl.IDCD_ID_SUB) as IDCD_ID_SUB,
  trim(tbl.IDCD_ID_TRANS) as IDCD_ID_TRANS,
  trim(tbl.MEME_CK) as MEME_CK
FROM bronze.tbl_clmd_diag tbl
GROUP BY
  trim(CLCL_ID),
  trim(CLMD_IDCD_MAN_IND),
  trim(CLMD_LOCK_TOKEN),
  trim(CLMD_POA_IND),
  trim(CLMD_TYPE),
  trim(IDCD_ID),
  trim(IDCD_ID_SUB),
  trim(IDCD_ID_TRANS),
  trim(MEME_CK);
CREATE OR REPLACE VIEW silver.V_tbl_ckpy_payee_sum AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CKPY_COMB_IND) as CKPY_COMB_IND,
  trim(tbl.CKPY_CURR_CKCK_SEQ) as CKPY_CURR_CKCK_SEQ,
  trim(tbl.CKPY_DEDUCT_AMT) as CKPY_DEDUCT_AMT,
  trim(tbl.CKPY_INT_AMT_NVL) as CKPY_INT_AMT_NVL,
  trim(tbl.CKPY_LOCK_TOKEN) as CKPY_LOCK_TOKEN,
  trim(tbl.CKPY_NET_AMT) as CKPY_NET_AMT,
  trim(tbl.CKPY_ORIG_AMT) as CKPY_ORIG_AMT,
  trim(tbl.CKPY_PAY_DT) as CKPY_PAY_DT,
  trim(tbl.CKPY_PAYEE_CK) as CKPY_PAYEE_CK,
  trim(tbl.CKPY_PAYEE_PR_ID) as CKPY_PAYEE_PR_ID,
  trim(tbl.CKPY_PAYEE_TYPE) as CKPY_PAYEE_TYPE,
  trim(tbl.CKPY_PER_END_DT) as CKPY_PER_END_DT,
  trim(tbl.CKPY_PYMT_TYPE) as CKPY_PYMT_TYPE,
  trim(tbl.CKPY_REF_ID) as CKPY_REF_ID,
  trim(tbl.CKPY_TYPE) as CKPY_TYPE,
  trim(tbl.LOBD_ID) as LOBD_ID
FROM bronze.tbl_ckpy_payee_sum tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CKPY_COMB_IND),
  trim(CKPY_CURR_CKCK_SEQ),
  trim(CKPY_DEDUCT_AMT),
  trim(CKPY_INT_AMT_NVL),
  trim(CKPY_LOCK_TOKEN),
  trim(CKPY_NET_AMT),
  trim(CKPY_ORIG_AMT),
  trim(CKPY_PAY_DT),
  trim(CKPY_PAYEE_CK),
  trim(CKPY_PAYEE_PR_ID),
  trim(CKPY_PAYEE_TYPE),
  trim(CKPY_PER_END_DT),
  trim(CKPY_PYMT_TYPE),
  trim(CKPY_REF_ID),
  trim(CKPY_TYPE),
  trim(LOBD_ID);
CREATE OR REPLACE VIEW silver.V_tbl_meme_member AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.GRGR_CK) as GRGR_CK,
  trim(tbl.MCRL_MEME_CREL_CD) as MCRL_MEME_CREL_CD,
  trim(tbl.MEME_BIRTH_DT) as MEME_BIRTH_DT,
  trim(tbl.MEME_CCC_END_DT) as MEME_CCC_END_DT,
  trim(tbl.MEME_CCC_START_DT) as MEME_CCC_START_DT,
  trim(tbl.MEME_CELL_PHONE) as MEME_CELL_PHONE,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.MEME_EDI_RE_CODE_NVL) as MEME_EDI_RE_CODE_NVL,
  trim(tbl.MEME_EDI_RE_SOURCE_NVL) as MEME_EDI_RE_SOURCE_NVL,
  trim(tbl.MEME_ELIG_DT) as MEME_ELIG_DT,
  trim(tbl.MEME_EOI_TERM_DT) as MEME_EOI_TERM_DT,
  trim(tbl.MEME_EXC_CRED_DAYS) as MEME_EXC_CRED_DAYS,
  trim(tbl.MEME_FAM_LINK_ID) as MEME_FAM_LINK_ID,
  trim(tbl.MEME_FIRST_NAME) as MEME_FIRST_NAME,
  trim(tbl.MEME_HEALTH_ID) as MEME_HEALTH_ID,
  trim(tbl.MEME_HICN) as MEME_HICN,
  trim(tbl.MEME_HIST_LINK_ID) as MEME_HIST_LINK_ID,
  trim(tbl.MEME_ID_NAME) as MEME_ID_NAME,
  trim(tbl.MEME_LAST_NAME) as MEME_LAST_NAME,
  trim(tbl.MEME_LAST_NAME_XLOW) as MEME_LAST_NAME_XLOW,
  trim(tbl.MEME_LATE_ENR_IND) as MEME_LATE_ENR_IND,
  trim(tbl.MEME_LOCK_TOKEN) as MEME_LOCK_TOKEN,
  trim(tbl.MEME_MARITAL_STATUS) as MEME_MARITAL_STATUS,
  trim(tbl.MEME_MCTR_ATYP) as MEME_MCTR_ATYP,
  trim(tbl.MEME_MCTR_CTZN_NVL) as MEME_MCTR_CTZN_NVL,
  trim(tbl.MEME_MCTR_ETHN_NVL) as MEME_MCTR_ETHN_NVL,
  trim(tbl.MEME_MCTR_GENP_NVL) as MEME_MCTR_GENP_NVL,
  trim(tbl.MEME_MCTR_LANG) as MEME_MCTR_LANG,
  trim(tbl.MEME_MCTR_RACE_NVL) as MEME_MCTR_RACE_NVL,
  trim(tbl.MEME_MCTR_STS) as MEME_MCTR_STS,
  trim(tbl.MEME_MEDCD_NO) as MEME_MEDCD_NO,
  trim(tbl.MEME_MID_INIT) as MEME_MID_INIT,
  trim(tbl.MEME_NEW_SIG_DT) as MEME_NEW_SIG_DT,
  trim(tbl.MEME_ORIG_EFF_DT) as MEME_ORIG_EFF_DT,
  trim(tbl.MEME_PRBL_EFF_DT) as MEME_PRBL_EFF_DT,
  trim(tbl.MEME_PRBL_IND) as MEME_PRBL_IND,
  trim(tbl.MEME_PREX_EFF_DT) as MEME_PREX_EFF_DT,
  trim(tbl.MEME_PREX_LIMIT1) as MEME_PREX_LIMIT1,
  trim(tbl.MEME_PREX_LIMIT2) as MEME_PREX_LIMIT2,
  trim(tbl.MEME_PREX_LIMIT3) as MEME_PREX_LIMIT3,
  trim(tbl.MEME_PREX_TERM_DT) as MEME_PREX_TERM_DT,
  trim(tbl.MEME_PRX_CRED_DAYS) as MEME_PRX_CRED_DAYS,
  trim(tbl.MEME_QUALIFY_DT) as MEME_QUALIFY_DT,
  trim(tbl.MEME_RECORD_NO) as MEME_RECORD_NO,
  trim(tbl.MEME_REL) as MEME_REL,
  trim(tbl.MEME_SEX) as MEME_SEX,
  trim(tbl.MEME_SFX) as MEME_SFX,
  trim(tbl.MEME_SSN) as MEME_SSN,
  trim(tbl.MEME_TITLE) as MEME_TITLE,
  trim(tbl.MEME_WRK_PHONE) as MEME_WRK_PHONE,
  trim(tbl.MEME_WRK_PHONE_EXT) as MEME_WRK_PHONE_EXT,
  trim(tbl.MEMM_ROW_ID) as MEMM_ROW_ID,
  trim(tbl.SBAD_TYPE_HOME) as SBAD_TYPE_HOME,
  trim(tbl.SBAD_TYPE_MAIL) as SBAD_TYPE_MAIL,
  trim(tbl.SBAD_TYPE_WORK) as SBAD_TYPE_WORK,
  trim(tbl.SBSB_CK) as SBSB_CK,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_meme_member tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(GRGR_CK),
  trim(MCRL_MEME_CREL_CD),
  trim(MEME_BIRTH_DT),
  trim(MEME_CCC_END_DT),
  trim(MEME_CCC_START_DT),
  trim(MEME_CELL_PHONE),
  trim(MEME_CK),
  trim(MEME_EDI_RE_CODE_NVL),
  trim(MEME_EDI_RE_SOURCE_NVL),
  trim(MEME_ELIG_DT),
  trim(MEME_EOI_TERM_DT),
  trim(MEME_EXC_CRED_DAYS),
  trim(MEME_FAM_LINK_ID),
  trim(MEME_FIRST_NAME),
  trim(MEME_HEALTH_ID),
  trim(MEME_HICN),
  trim(MEME_HIST_LINK_ID),
  trim(MEME_ID_NAME),
  trim(MEME_LAST_NAME),
  trim(MEME_LAST_NAME_XLOW),
  trim(MEME_LATE_ENR_IND),
  trim(MEME_LOCK_TOKEN),
  trim(MEME_MARITAL_STATUS),
  trim(MEME_MCTR_ATYP),
  trim(MEME_MCTR_CTZN_NVL),
  trim(MEME_MCTR_ETHN_NVL),
  trim(MEME_MCTR_GENP_NVL),
  trim(MEME_MCTR_LANG),
  trim(MEME_MCTR_RACE_NVL),
  trim(MEME_MCTR_STS),
  trim(MEME_MEDCD_NO),
  trim(MEME_MID_INIT),
  trim(MEME_NEW_SIG_DT),
  trim(MEME_ORIG_EFF_DT),
  trim(MEME_PRBL_EFF_DT),
  trim(MEME_PRBL_IND),
  trim(MEME_PREX_EFF_DT),
  trim(MEME_PREX_LIMIT1),
  trim(MEME_PREX_LIMIT2),
  trim(MEME_PREX_LIMIT3),
  trim(MEME_PREX_TERM_DT),
  trim(MEME_PRX_CRED_DAYS),
  trim(MEME_QUALIFY_DT),
  trim(MEME_RECORD_NO),
  trim(MEME_REL),
  trim(MEME_SEX),
  trim(MEME_SFX),
  trim(MEME_SSN),
  trim(MEME_TITLE),
  trim(MEME_WRK_PHONE),
  trim(MEME_WRK_PHONE_EXT),
  trim(MEMM_ROW_ID),
  trim(SBAD_TYPE_HOME),
  trim(SBAD_TYPE_MAIL),
  trim(SBAD_TYPE_WORK),
  trim(SBSB_CK),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_sbsb_subsc AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.GRGR_CK) as GRGR_CK,
  trim(tbl.MCBR_CK) as MCBR_CK,
  trim(tbl.SBAD_TYPE_HOME) as SBAD_TYPE_HOME,
  trim(tbl.SBAD_TYPE_MAIL) as SBAD_TYPE_MAIL,
  trim(tbl.SBAD_TYPE_WORK) as SBAD_TYPE_WORK,
  trim(tbl.SBSB_CK) as SBSB_CK,
  trim(tbl.SBSB_CONV_DT) as SBSB_CONV_DT,
  trim(tbl.SBSB_EFT_IND) as SBSB_EFT_IND,
  trim(tbl.SBSB_EMPLOY_ID) as SBSB_EMPLOY_ID,
  trim(tbl.SBSB_FI) as SBSB_FI,
  trim(tbl.SBSB_FIRST_NAME) as SBSB_FIRST_NAME,
  trim(tbl.SBSB_HIRE_DT) as SBSB_HIRE_DT,
  trim(tbl.SBSB_ID) as SBSB_ID,
  trim(tbl.SBSB_LAST_NAME) as SBSB_LAST_NAME,
  trim(tbl.SBSB_LAST_NAME_XLOW) as SBSB_LAST_NAME_XLOW,
  trim(tbl.SBSB_LOCK_TOKEN) as SBSB_LOCK_TOKEN,
  trim(tbl.SBSB_MCTR_SRSN) as SBSB_MCTR_SRSN,
  trim(tbl.SBSB_MCTR_STS) as SBSB_MCTR_STS,
  trim(tbl.SBSB_MCTR_VIP) as SBSB_MCTR_VIP,
  trim(tbl.SBSB_MID_INIT) as SBSB_MID_INIT,
  trim(tbl.SBSB_MLR_EFT_IND_NVL) as SBSB_MLR_EFT_IND_NVL,
  trim(tbl.SBSB_ORIG_EFF_DT) as SBSB_ORIG_EFF_DT,
  trim(tbl.SBSB_PAY_CL_METH) as SBSB_PAY_CL_METH,
  trim(tbl.SBSB_PAY_FSAC_METH) as SBSB_PAY_FSAC_METH,
  trim(tbl.SBSB_PRCS_STS) as SBSB_PRCS_STS,
  trim(tbl.SBSB_RECD_DT) as SBSB_RECD_DT,
  trim(tbl.SBSB_RETIRE_DT) as SBSB_RETIRE_DT,
  trim(tbl.SBSB_SIG_DT) as SBSB_SIG_DT,
  trim(tbl.SBSB_TITLE) as SBSB_TITLE,
  trim(tbl.SYS_BITMAP_NVL) as SYS_BITMAP_NVL,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_OFFSET_NVL) as SYS_LAST_OFFSET_NVL,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_sbsb_subsc tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(GRGR_CK),
  trim(MCBR_CK),
  trim(SBAD_TYPE_HOME),
  trim(SBAD_TYPE_MAIL),
  trim(SBAD_TYPE_WORK),
  trim(SBSB_CK),
  trim(SBSB_CONV_DT),
  trim(SBSB_EFT_IND),
  trim(SBSB_EMPLOY_ID),
  trim(SBSB_FI),
  trim(SBSB_FIRST_NAME),
  trim(SBSB_HIRE_DT),
  trim(SBSB_ID),
  trim(SBSB_LAST_NAME),
  trim(SBSB_LAST_NAME_XLOW),
  trim(SBSB_LOCK_TOKEN),
  trim(SBSB_MCTR_SRSN),
  trim(SBSB_MCTR_STS),
  trim(SBSB_MCTR_VIP),
  trim(SBSB_MID_INIT),
  trim(SBSB_MLR_EFT_IND_NVL),
  trim(SBSB_ORIG_EFF_DT),
  trim(SBSB_PAY_CL_METH),
  trim(SBSB_PAY_FSAC_METH),
  trim(SBSB_PRCS_STS),
  trim(SBSB_RECD_DT),
  trim(SBSB_RETIRE_DT),
  trim(SBSB_SIG_DT),
  trim(SBSB_TITLE),
  trim(SYS_BITMAP_NVL),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_OFFSET_NVL),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_mepe_prcs_elig AS
SELECT
  trim(tbl.CSCS_ID) as CSCS_ID,
  trim(tbl.CSPD_CAT) as CSPD_CAT,
  trim(tbl.CSPI_ID) as CSPI_ID,
  trim(tbl.EXCD_ID) as EXCD_ID,
  trim(tbl.GRGR_CK) as GRGR_CK,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.MEPE_BL_ELIG_IND_NVL) as MEPE_BL_ELIG_IND_NVL,
  trim(tbl.MEPE_CREATE_DTM) as MEPE_CREATE_DTM,
  trim(tbl.MEPE_EFF_DT) as MEPE_EFF_DT,
  trim(tbl.MEPE_ELIG_IND) as MEPE_ELIG_IND,
  trim(tbl.MEPE_ELIG_OVR_IND) as MEPE_ELIG_OVR_IND,
  trim(tbl.MEPE_FI) as MEPE_FI,
  trim(tbl.MEPE_HAS_MEDX_IND) as MEPE_HAS_MEDX_IND,
  trim(tbl.MEPE_HAS_WARN_CD) as MEPE_HAS_WARN_CD,
  trim(tbl.MEPE_LOCK_TOKEN) as MEPE_LOCK_TOKEN,
  trim(tbl.MEPE_MCTR_RSN) as MEPE_MCTR_RSN,
  trim(tbl.MEPE_PLAN_ENTRY_DT) as MEPE_PLAN_ENTRY_DT,
  trim(tbl.MEPE_PRCS_STS) as MEPE_PRCS_STS,
  trim(tbl.MEPE_SOURCE) as MEPE_SOURCE,
  trim(tbl.MEPE_SYS_INEL_CD) as MEPE_SYS_INEL_CD,
  trim(tbl.MEPE_TERM_DT) as MEPE_TERM_DT,
  trim(tbl.PDPD_ID) as PDPD_ID,
  trim(tbl.SGSG_CK) as SGSG_CK
FROM bronze.tbl_mepe_prcs_elig tbl
GROUP BY
  trim(CSCS_ID),
  trim(CSPD_CAT),
  trim(CSPI_ID),
  trim(EXCD_ID),
  trim(GRGR_CK),
  trim(MEME_CK),
  trim(MEPE_BL_ELIG_IND_NVL),
  trim(MEPE_CREATE_DTM),
  trim(MEPE_EFF_DT),
  trim(MEPE_ELIG_IND),
  trim(MEPE_ELIG_OVR_IND),
  trim(MEPE_FI),
  trim(MEPE_HAS_MEDX_IND),
  trim(MEPE_HAS_WARN_CD),
  trim(MEPE_LOCK_TOKEN),
  trim(MEPE_MCTR_RSN),
  trim(MEPE_PLAN_ENTRY_DT),
  trim(MEPE_PRCS_STS),
  trim(MEPE_SOURCE),
  trim(MEPE_SYS_INEL_CD),
  trim(MEPE_TERM_DT),
  trim(PDPD_ID),
  trim(SGSG_CK);
CREATE OR REPLACE VIEW silver.V_tbl_clhp_hosp AS
SELECT
  trim(tbl.AGRG_ID) as AGRG_ID,
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CLHP_ADM_DT) as CLHP_ADM_DT,
  trim(tbl.CLHP_ADM_HOUR_CD) as CLHP_ADM_HOUR_CD,
  trim(tbl.CLHP_ADM_SOURCE) as CLHP_ADM_SOURCE,
  trim(tbl.CLHP_ADM_TYP) as CLHP_ADM_TYP,
  trim(tbl.CLHP_BILL_CLASS) as CLHP_BILL_CLASS,
  trim(tbl.CLHP_BIRTH_WGT) as CLHP_BIRTH_WGT,
  trim(tbl.CLHP_COVD_DAYS) as CLHP_COVD_DAYS,
  trim(tbl.CLHP_DC_DT) as CLHP_DC_DT,
  trim(tbl.CLHP_DC_HOUR_CD) as CLHP_DC_HOUR_CD,
  trim(tbl.CLHP_DC_STAT) as CLHP_DC_STAT,
  trim(tbl.CLHP_FAC_TYPE) as CLHP_FAC_TYPE,
  trim(tbl.CLHP_FREQUENCY) as CLHP_FREQUENCY,
  trim(tbl.CLHP_ICD_QUAL_IND) as CLHP_ICD_QUAL_IND,
  trim(tbl.CLHP_INPUT_AGRG_ID) as CLHP_INPUT_AGRG_ID,
  trim(tbl.CLHP_IPCD_METH) as CLHP_IPCD_METH,
  trim(tbl.CLHP_LOCK_TOKEN) as CLHP_LOCK_TOKEN,
  trim(tbl.CLHP_MED_REC_NO) as CLHP_MED_REC_NO,
  trim(tbl.CLHP_NOA_RECD_DT_NVL) as CLHP_NOA_RECD_DT_NVL,
  trim(tbl.CLHP_PRPR_AD_NPI) as CLHP_PRPR_AD_NPI,
  trim(tbl.CLHP_PRPR_AD_TAX) as CLHP_PRPR_AD_TAX,
  trim(tbl.CLHP_PRPR_ID_ADM) as CLHP_PRPR_ID_ADM,
  trim(tbl.CLHP_PRPR_ID_OPER) as CLHP_PRPR_ID_OPER,
  trim(tbl.CLHP_PRPR_ID_OTH1) as CLHP_PRPR_ID_OTH1,
  trim(tbl.CLHP_PRPR_ID_OTH2) as CLHP_PRPR_ID_OTH2,
  trim(tbl.CLHP_PRPR_O1_NPI) as CLHP_PRPR_O1_NPI,
  trim(tbl.CLHP_PRPR_O1_TAX) as CLHP_PRPR_O1_TAX,
  trim(tbl.CLHP_PRPR_O2_NPI) as CLHP_PRPR_O2_NPI,
  trim(tbl.CLHP_PRPR_O2_TAX) as CLHP_PRPR_O2_TAX,
  trim(tbl.CLHP_PRPR_OP_NPI) as CLHP_PRPR_OP_NPI,
  trim(tbl.CLHP_PRPR_OP_TAX) as CLHP_PRPR_OP_TAX,
  trim(tbl.CLHP_STAMENT_FR_DT) as CLHP_STAMENT_FR_DT,
  trim(tbl.CLHP_STAMENT_TO_DT) as CLHP_STAMENT_TO_DT,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.SYS_DBUSER_ID) as SYS_DBUSER_ID,
  trim(tbl.SYS_LAST_UPD_DTM) as SYS_LAST_UPD_DTM,
  trim(tbl.SYS_USUS_ID) as SYS_USUS_ID
FROM bronze.tbl_clhp_hosp tbl
GROUP BY
  trim(AGRG_ID),
  trim(ATXR_SOURCE_ID),
  trim(CLCL_ID),
  trim(CLHP_ADM_DT),
  trim(CLHP_ADM_HOUR_CD),
  trim(CLHP_ADM_SOURCE),
  trim(CLHP_ADM_TYP),
  trim(CLHP_BILL_CLASS),
  trim(CLHP_BIRTH_WGT),
  trim(CLHP_COVD_DAYS),
  trim(CLHP_DC_DT),
  trim(CLHP_DC_HOUR_CD),
  trim(CLHP_DC_STAT),
  trim(CLHP_FAC_TYPE),
  trim(CLHP_FREQUENCY),
  trim(CLHP_ICD_QUAL_IND),
  trim(CLHP_INPUT_AGRG_ID),
  trim(CLHP_IPCD_METH),
  trim(CLHP_LOCK_TOKEN),
  trim(CLHP_MED_REC_NO),
  trim(CLHP_NOA_RECD_DT_NVL),
  trim(CLHP_PRPR_AD_NPI),
  trim(CLHP_PRPR_AD_TAX),
  trim(CLHP_PRPR_ID_ADM),
  trim(CLHP_PRPR_ID_OPER),
  trim(CLHP_PRPR_ID_OTH1),
  trim(CLHP_PRPR_ID_OTH2),
  trim(CLHP_PRPR_O1_NPI),
  trim(CLHP_PRPR_O1_TAX),
  trim(CLHP_PRPR_O2_NPI),
  trim(CLHP_PRPR_O2_TAX),
  trim(CLHP_PRPR_OP_NPI),
  trim(CLHP_PRPR_OP_TAX),
  trim(CLHP_STAMENT_FR_DT),
  trim(CLHP_STAMENT_TO_DT),
  trim(MEME_CK),
  trim(SYS_DBUSER_ID),
  trim(SYS_LAST_UPD_DTM),
  trim(SYS_USUS_ID);
CREATE OR REPLACE VIEW silver.V_tbl_cddl_cl_line AS
SELECT
  trim(tbl.ATXR_SOURCE_ID) as ATXR_SOURCE_ID,
  trim(tbl.CDDL_AG_PRICE) as CDDL_AG_PRICE,
  trim(tbl.CDDL_ALLOW) as CDDL_ALLOW,
  trim(tbl.CDDL_ALTDP_EXCD_ID) as CDDL_ALTDP_EXCD_ID,
  trim(tbl.CDDL_CAP_IND) as CDDL_CAP_IND,
  trim(tbl.CDDL_CGPY_ACCT_CAT) as CDDL_CGPY_ACCT_CAT,
  trim(tbl.CDDL_CGPY_EXP_CAT) as CDDL_CGPY_EXP_CAT,
  trim(tbl.CDDL_CHG_AMT) as CDDL_CHG_AMT,
  trim(tbl.CDDL_CL_NTWK_IND) as CDDL_CL_NTWK_IND,
  trim(tbl.CDDL_CLMD_TYPE2) as CDDL_CLMD_TYPE2,
  trim(tbl.CDDL_CLMD_TYPE3) as CDDL_CLMD_TYPE3,
  trim(tbl.CDDL_CLMD_TYPE4) as CDDL_CLMD_TYPE4,
  trim(tbl.CDDL_COINS_AMT) as CDDL_COINS_AMT,
  trim(tbl.CDDL_CONSIDER_CHG) as CDDL_CONSIDER_CHG,
  trim(tbl.CDDL_COPAY_AMT) as CDDL_COPAY_AMT,
  trim(tbl.CDDL_CUR_STS) as CDDL_CUR_STS,
  trim(tbl.CDDL_DED_AC_NO) as CDDL_DED_AC_NO,
  trim(tbl.CDDL_DED_AMT) as CDDL_DED_AMT,
  trim(tbl.CDDL_DIS_PA_LIAB) as CDDL_DIS_PA_LIAB,
  trim(tbl.CDDL_DISALL_AMT) as CDDL_DISALL_AMT,
  trim(tbl.CDDL_DISALL_EXCD) as CDDL_DISALL_EXCD,
  trim(tbl.CDDL_DISC_AMT) as CDDL_DISC_AMT,
  trim(tbl.CDDL_DP_PRICE) as CDDL_DP_PRICE,
  trim(tbl.CDDL_EOB_EXCD) as CDDL_EOB_EXCD,
  trim(tbl.CDDL_EXT_LINE_NO) as CDDL_EXT_LINE_NO,
  trim(tbl.CDDL_FAM_IND) as CDDL_FAM_IND,
  trim(tbl.CDDL_FROM_DT) as CDDL_FROM_DT,
  trim(tbl.CDDL_GWID) as CDDL_GWID,
  trim(tbl.CDDL_IP_PRICE) as CDDL_IP_PRICE,
  trim(tbl.CDDL_LOCK_TOKEN) as CDDL_LOCK_TOKEN,
  trim(tbl.CDDL_OOP_CALC_BASE) as CDDL_OOP_CALC_BASE,
  trim(tbl.CDDL_PAID_AMT) as CDDL_PAID_AMT,
  trim(tbl.CDDL_PF_PRICE) as CDDL_PF_PRICE,
  trim(tbl.CDDL_PR_LN_CNTL_NO_NVL) as CDDL_PR_LN_CNTL_NO_NVL,
  trim(tbl.CDDL_PR_PYMT_AMT) as CDDL_PR_PYMT_AMT,
  trim(tbl.CDDL_PRED_CLCL_ID) as CDDL_PRED_CLCL_ID,
  trim(tbl.CDDL_PRICE_IND) as CDDL_PRICE_IND,
  trim(tbl.CDDL_PRPG_IND) as CDDL_PRPG_IND,
  trim(tbl.CDDL_REF_IND) as CDDL_REF_IND,
  trim(tbl.CDDL_REFSV_SEQ_NO) as CDDL_REFSV_SEQ_NO,
  trim(tbl.CDDL_RISK_WH_AMT) as CDDL_RISK_WH_AMT,
  trim(tbl.CDDL_SB_PYMT_AMT) as CDDL_SB_PYMT_AMT,
  trim(tbl.CDDL_SEQ_NO) as CDDL_SEQ_NO,
  trim(tbl.CDDL_SURF) as CDDL_SURF,
  trim(tbl.CDDL_TOOTH_BEG) as CDDL_TOOTH_BEG,
  trim(tbl.CDDL_TOOTH_END) as CDDL_TOOTH_END,
  trim(tbl.CDDL_TOOTH_NO) as CDDL_TOOTH_NO,
  trim(tbl.CDDL_TOT_PA_LIAB) as CDDL_TOT_PA_LIAB,
  trim(tbl.CDDL_UMREF_ID) as CDDL_UMREF_ID,
  trim(tbl.CDDL_UNITS) as CDDL_UNITS,
  trim(tbl.CDDL_UNITS_ALLOW) as CDDL_UNITS_ALLOW,
  trim(tbl.CDDL_VBB_EXCD_ID) as CDDL_VBB_EXCD_ID,
  trim(tbl.CGCG_ID) as CGCG_ID,
  trim(tbl.CGCG_RULE) as CGCG_RULE,
  trim(tbl.CGPY_PFX) as CGPY_PFX,
  trim(tbl.CLCL_ID) as CLCL_ID,
  trim(tbl.CRFD_FUND_ID) as CRFD_FUND_ID,
  trim(tbl.CRPL_POOL_ID) as CRPL_POOL_ID,
  trim(tbl.DEDE_PFX) as DEDE_PFX,
  trim(tbl.DPCG_DP_ID_ALT) as DPCG_DP_ID_ALT,
  trim(tbl.DPDP_ID) as DPDP_ID,
  trim(tbl.DPPC_PRICE_ID) as DPPC_PRICE_ID,
  trim(tbl.DPPY_PFX) as DPPY_PFX,
  trim(tbl.DPTC_CD) as DPTC_CD,
  trim(tbl.IDCD_ID) as IDCD_ID,
  trim(tbl.IDCD_ID_REL) as IDCD_ID_REL,
  trim(tbl.IDCD_ID_SUB) as IDCD_ID_SUB,
  trim(tbl.IDCD_ID_SUB_REL) as IDCD_ID_SUB_REL,
  trim(tbl.IDCD_ID_TRANS) as IDCD_ID_TRANS,
  trim(tbl.IDCD_ID_TRANS_REL) as IDCD_ID_TRANS_REL,
  trim(tbl.LOBD_ID) as LOBD_ID,
  trim(tbl.LTLT_PFX) as LTLT_PFX,
  trim(tbl.MEME_CK) as MEME_CK,
  trim(tbl.PDVC_LOBD_PTR) as PDVC_LOBD_PTR,
  trim(tbl.PRPR_ID) as PRPR_ID,
  trim(tbl.PSDC_ID) as PSDC_ID,
  trim(tbl.RPTC_RPT_CAT) as RPTC_RPT_CAT,
  trim(tbl.UTUT_CD) as UTUT_CD,
  trim(tbl.VBBD_RULE) as VBBD_RULE
FROM bronze.tbl_cddl_cl_line tbl
GROUP BY
  trim(ATXR_SOURCE_ID),
  trim(CDDL_AG_PRICE),
  trim(CDDL_ALLOW),
  trim(CDDL_ALTDP_EXCD_ID),
  trim(CDDL_CAP_IND),
  trim(CDDL_CGPY_ACCT_CAT),
  trim(CDDL_CGPY_EXP_CAT),
  trim(CDDL_CHG_AMT),
  trim(CDDL_CL_NTWK_IND),
  trim(CDDL_CLMD_TYPE2),
  trim(CDDL_CLMD_TYPE3),
  trim(CDDL_CLMD_TYPE4),
  trim(CDDL_COINS_AMT),
  trim(CDDL_CONSIDER_CHG),
  trim(CDDL_COPAY_AMT),
  trim(CDDL_CUR_STS),
  trim(CDDL_DED_AC_NO),
  trim(CDDL_DED_AMT),
  trim(CDDL_DIS_PA_LIAB),
  trim(CDDL_DISALL_AMT),
  trim(CDDL_DISALL_EXCD),
  trim(CDDL_DISC_AMT),
  trim(CDDL_DP_PRICE),
  trim(CDDL_EOB_EXCD),
  trim(CDDL_EXT_LINE_NO),
  trim(CDDL_FAM_IND),
  trim(CDDL_FROM_DT),
  trim(CDDL_GWID),
  trim(CDDL_IP_PRICE),
  trim(CDDL_LOCK_TOKEN),
  trim(CDDL_OOP_CALC_BASE),
  trim(CDDL_PAID_AMT),
  trim(CDDL_PF_PRICE),
  trim(CDDL_PR_LN_CNTL_NO_NVL),
  trim(CDDL_PR_PYMT_AMT),
  trim(CDDL_PRED_CLCL_ID),
  trim(CDDL_PRICE_IND),
  trim(CDDL_PRPG_IND),
  trim(CDDL_REF_IND),
  trim(CDDL_REFSV_SEQ_NO),
  trim(CDDL_RISK_WH_AMT),
  trim(CDDL_SB_PYMT_AMT),
  trim(CDDL_SEQ_NO),
  trim(CDDL_SURF),
  trim(CDDL_TOOTH_BEG),
  trim(CDDL_TOOTH_END),
  trim(CDDL_TOOTH_NO),
  trim(CDDL_TOT_PA_LIAB),
  trim(CDDL_UMREF_ID),
  trim(CDDL_UNITS),
  trim(CDDL_UNITS_ALLOW),
  trim(CDDL_VBB_EXCD_ID),
  trim(CGCG_ID),
  trim(CGCG_RULE),
  trim(CGPY_PFX),
  trim(CLCL_ID),
  trim(CRFD_FUND_ID),
  trim(CRPL_POOL_ID),
  trim(DEDE_PFX),
  trim(DPCG_DP_ID_ALT),
  trim(DPDP_ID),
  trim(DPPC_PRICE_ID),
  trim(DPPY_PFX),
  trim(DPTC_CD),
  trim(IDCD_ID),
  trim(IDCD_ID_REL),
  trim(IDCD_ID_SUB),
  trim(IDCD_ID_SUB_REL),
  trim(IDCD_ID_TRANS),
  trim(IDCD_ID_TRANS_REL),
  trim(LOBD_ID),
  trim(LTLT_PFX),
  trim(MEME_CK),
  trim(PDVC_LOBD_PTR),
  trim(PRPR_ID),
  trim(PSDC_ID),
  trim(RPTC_RPT_CAT),
  trim(UTUT_CD),
  trim(VBBD_RULE);
